### ISSUE TITLE
Complete translation: Catalan

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#102]
**Provide the two-letter code of the existing language**
`ca`

**Provide the lines, that are still English and should be translated**
- 32-33
- 40-41
- 44
- 46-47
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/ca/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/ca/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@altmas5 @Leos1113 Would one of you like to update the Catalan translation again? That would be awesome!

**Comment by altmas5** [comment]
> @altmas5 @Leos1113 Would one of you like to update the Catalan translation again? That would be awesome!

Sure, I'll sync my fork with the current upstream and update the translation.

**Comment by devmount** [comment]
Awesome, many thanks!

**Comment by altmas5** [comment]
> Awesome, many thanks!

Anytime!
