### ISSUE TITLE
Complete translation: Czech

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#103]
**Provide the two-letter code of the existing language**
`cs`

**Provide the lines, that are still English and should be translated**
- 32-33
- 40-41
- 44
- 46-47
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/cs/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/cs/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@ajyan @martinsustek Would one of you like to update the Czech translation again? That would be awesome!

**Comment by martinsustek** [comment]
pull request #126
