### ISSUE TITLE
Complete translation: Spanish

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#105]
**Provide the two-letter code of the existing language**
`es`

**Provide the lines, that are still English and should be translated**
- 32-33
- 40-41
- 44
- 46-47
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/es/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/es/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@roninJosue @SabrinaFZ Would one of you like to update the Spanish translation again? That would be awesome!

**Comment by roninJosue** [comment]
Hello, yeah I going to do it :)

**Comment by devmount** [comment]
Nice, thank you!

**Comment by devmount** [comment]
Hey Reynaldo, please have a look at #135 - we'll try to improve the translation process.
