### ISSUE TITLE
Complete translation: French

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#106]
**Provide the two-letter code of the existing language**
`fr`

**Provide the lines, that are still English and should be translated**
- 32-33
- 40-41
- 44
- 46-47
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/fr/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/fr/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@feyre-2001 @antoinevth @aurelienrouze Would one of you like to update the French translation again? That would be awesome!

**Comment by aurelienrouze** [comment]
Hi, 

I'm on it ;)

**Comment by aurelienrouze** [comment]
There is the translation. 

Have a great day !
