### ISSUE TITLE
Complete translation: Italian

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#108]
**Provide the two-letter code of the existing language**
`it`

**Provide the lines, that are still English and should be translated**
- 32-33
- 40-41
- 44
- 46-47
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/it/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/it/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@edmael @leobia Would one of you like to update the Italian translation again? That would be awesome!

**Comment by leobia** [comment]
There you go :) As I wrote on the description I did not translate rows 93-94 because I think that they are more understandable that way in Italian
