### ISSUE TITLE
Complete translation: Japanese

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#109]
**Provide the two-letter code of the existing language**
`ja`

**Provide the lines, that are still English and should be translated**
- 32-33
- 40-41
- 44
- 46-47
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/ja/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/ja/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@marcelstoer Would you like to update the Japanese translation again? That would be awesome!

**Comment by marcelstoer** [comment]
Accepted

**Comment by marcelstoer** [comment]
Btw, have you considered moving to a cloud/browser-based localization platform? I can imagine that it would greatly simplify your life and ours.

**Comment by devmount** [comment]
Yes I considered it when this project started and decided to wait and see if there would be enough interest in different translations.  Now with around 20 languages you're right, we need something better than GitHub issues 😅

Do you have experience with these tools? Would you recommend one?

Thank you for this suggestion.

**Comment by devmount** [comment]
I found this tool and might give it a try:
https://gitlocalize.com

**Comment by marcelstoer** [comment]
Little to no experience, sorry. A while back I helped translate a major WordPress plugin on GlotPress; is a bit dated. GitLocalize looks really promising.

**Comment by devmount** [comment]
Ok cool, thanks again for your valuable input. I'll create a new issue to discuss GitLocalize with all translators and get started there.
