### ISSUE TITLE
Additional Bar Chart: Emails per Month of Year

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#11]
**Is your feature request related to a problem? Please describe.**
No problem. Just completing the already existing analytics.

**Describe the solution you'd like**
A bar chart showing the number of emails that occurred in that month, showing a possible dependency of emails on seasons of the year.

**Describe alternatives you've considered**
A possible alternative is just showing email count per quarter of year, but months would be more precise.

**Additional context**
None.

**Comment by ianzucker1** [comment]
Indeed, could this be filtered through a pull down menu or inclusion / exclusion (e.g. February, March, June and July).

**Comment by kerlon5** [comment]
Hello. I'm working on this issue. Solution based on monthsChartData function.  What is your vision for chart title and description, it's positioning among other charts? 'Months' and 'Total number of emails per month' fits well but used in another chart. Also, it would be nice to have translations for arrays of labels used in functions (like ['Jan', 'Feb'...).

**Comment by devmount** [comment]
Awesome and thanks in advance 👏🏻!
Yes, 'Months' and 'Total number of emails per month' actually fits better than for the existing chart. Please reuse this title and description and I will rename the other ones with a more fitting title/description.
Please position it in a new row after the last charts, there will be some layout improvement soon where the charts get repositioned.
Very good point - please just use the hardcoded English month abbreviations for now, I will soon add a functions that provides the weekday/month names for the corresponding locale.

**Comment by kerlon5** [comment]
![image](https://user-images.githubusercontent.com/26476861/94786066-ee95f380-03e9-11eb-8199-0e6d82be1ec2.png)
Screenshot for layout improvement. Now heatmap in one line with bar chart looks like on image (2). Does it look good? On image (1) caption and rows wrapped in additional divs with  flex-direction: column; justify-content: space-between;

**Comment by devmount** [comment]
Thank you for this suggestion, for the scope of this issue, please just position the new chart in a new row after the last charts. Layout improvement will be discussed in another issue.
