### ISSUE TITLE
Complete translation: Portuguese

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#111]
**Provide the two-letter code of the existing language**
`pt`

**Provide the lines, that are still English and should be translated**
- 32-33
- 40-41
- 44
- 46-47
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/pt/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/pt/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@di3goCS and @printf-ana Would one of you like to update the Portuguese translation again? That would be awesome!

**Comment by di3goCS** [comment]
Oh! I guess i could do it next week! :)

**Comment by devmount** [comment]
Awesome, thanks!

**Comment by devmount** [comment]
Hey Diego, please have a look at #135 - we'll try to improve the translation process.
