### ISSUE TITLE
Complete translation: Swedish

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#113]
**Provide the two-letter code of the existing language**
`sv`

**Provide the lines, that are still English and should be translated**
- 32-33
- 40-41
- 44
- 46-47
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/sv/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/sv/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@FrejBjornsson Would you like to update the Simplified Chinese translation again? That would be awesome!

**Comment by FrejBjornsson** [comment]
If you mean the Swedish translation I'd be happy to help! @devmount

**Comment by devmount** [comment]
Sorry, copy and paste 🙈😅 Yes I meant Swedish! Thanks so much! 👏🏻

**Comment by FrejBjornsson** [comment]
I created a PR. Tell me if you need anything else or if something is missing.  👍
