### ISSUE TITLE
Complete translation: Simplified Chinese

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#116]
**Provide the two-letter code of the existing language**
`zh-cn`

**Provide the lines, that are still English and should be translated**
- 32-33
- 40-41
- 44
- 46-47
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/zh-cn/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/zh-cn/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@jswildcards Would you like to update the Simplified Chinese translation again? That would be awesome!

**Comment by jswildcards** [comment]
@devmount Sure!
