### ISSUE TITLE
Complete translation: Traditional Chinese

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#117]
**Provide the two-letter code of the existing language**
`zh-tw`

**Provide the lines, that are still English and should be translated**
- 32-33
- 40-41
- 44
- 46-47
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/zh-tw/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/zh-tw/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@Hsins Would you like to update the Traditional Chinese translation agian? That would be awesome!

**Comment by Hsins** [comment]
I have updated the Traditional Chinese translation in the PR https://github.com/devmount/third-stats/pull/121.
