### ISSUE TITLE
Additional Heat Map: Last year

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#12]
**Is your feature request related to a problem? Please describe.**
No problem. Just completing the already existing analytics.

**Describe the solution you'd like**
A heat map showing the number of emails for the last year per day (meaning the previous 365 days from today), similar to the contributions heat map of GitHub. Vertical axis is the day of week (7 values), horizontal axis is the week number (52-53 values).
Also there could be Buttons for every past year (again inspired by GitHub), to toggle the HeatMap data for the corresponding year.

**Describe alternatives you've considered**
A possible alternative is just showing number of emails for the last month, but for the last year would give a much better overview.

**Additional context**
None.

**Comment by ianzucker1** [comment]
I would like to complement this by asking if it were possible to have 'Sunday' at the beginning of the week? Appreciating that this is not necessarily the standard for everyone, across the world.

**Comment by devmount** [comment]
@ianzucker1 Good point. This also relates to the existing heatmaps (temporal distributions), currently starting on monday. Please open [a feature request](https://github.com/devmount/third-stats/issues/new?template=feature_request.md) for this and we'll see how we can make this possible (I think we need some kinde of general add-on options here).
