### ISSUE TITLE
Replace "open external link" icon with "dashboard" like icon

### ISSUE THREAD

**Issue by koobs** [devmount/third-stats#129]
**Is your feature request related to a problem? Please describe.**

Understanding the context and semantics of UI graphics is important. The current icon in the third-stats toolbar menu is a "square with top right facing arrow". This is usually used to mean 'open external link'.

![third-1](https://user-images.githubusercontent.com/1011612/98752788-d509a380-23ba-11eb-948f-783b91242d9b.png)

While this loosely might make sense relative to the function exposed by clicking the icon ("open full third stats window/tab"), the present icon represents more **what** happens, rather than the **function/feature** relevent to third stats that it relates to (graphs, dashboard, etc).

I believe there are better icons to represent the function.

**Describe the solution you'd like**

An icon that represents 'graphs' or 'dashboard' or similar. 

In the first example I have used the third stats icon, which happens to be 'graphy'. However, It may not make sense to use the logo verbatim, as it would duplicate the toolbar menu icon, which is also relatively close to where the 'open dashboard' icon is. Additionally, the logo may not carry the same semantics, as it might relate strongly (and only) to the brand itself, rather than the function.

![third-after-1](https://user-images.githubusercontent.com/1011612/98752799-da66ee00-23ba-11eb-80b9-02e762f238eb.png)

The second variation, switches the location of the icon (right to left)

![third-after-2](https://user-images.githubusercontent.com/1011612/98752805-dd61de80-23ba-11eb-92b0-74507e1f211d.png)

Icons that I believe would be most suitable, that are from FontAwesome:

![2020-11-11 11_47_33-Graph Icons _ Font Awesome — Firefox Nightly](https://user-images.githubusercontent.com/1011612/98751905-eea9eb80-23b8-11eb-9b26-3e1a2cd8befe.png)

I would use **chart-area**, as a first choice, and **chart-bar** as second choice.

**Describe alternatives you've considered**

* The third stats logo
* Standard logo's for 'dashboards', 'graphs', 'metrics' and 'open new window'

**Additional context**

 * May want to consider an additional UI affordance for the icon, such that it is more obvious that it is interactive (clickable). An on-hover style change may be suitable. Alternatively, the icon may be styled to look 'more button like'

**Comment by devmount** [comment]
Thanks so much @koobs for this extremely nice and detailed explanations 👏🏻 Here are my thoughts:

1. I wouldn't reuse the logo again for the same reason you already mentioned (too close to the toolbar logo icon)
2. In this project I use the [tabler icons](https://tablericons.com/), so these would be the icons that are available (my favorite is the `chart-area` I think):
![image](https://user-images.githubusercontent.com/5441654/99350292-44413500-289e-11eb-8df4-886a00c0bb70.png)
3. I consider revamping the layout a little bit: The loading spinner would be semantically more suitable right next to the accounts text (as the accounts numbers are loading) and the chart icon in the same line on the far right.
4. Yes, there definitely has to be a hover effect for the icon

What do you think?

**Comment by devmount** [comment]
Ok I played around a little bit and ended up using a grid/dashboard icon:
![image](https://user-images.githubusercontent.com/5441654/99623925-73d27780-2a2d-11eb-8ead-0ca43ff1e3cf.png)

What do you think?

**Comment by koobs** [comment]
@devmount Definitely +1 on chart-area, i think 'grid' has the same issue as OP

**Comment by devmount** [comment]
Thank you for your feedback. I implemented the chart-area icon now:
![image](https://user-images.githubusercontent.com/5441654/99759282-cc1f7d00-2af2-11eb-8feb-26388c85377e.png)

And an additional tooltip on mouseover to explain the action:
![image](https://user-images.githubusercontent.com/5441654/99760194-70a1bf00-2af3-11eb-8bf7-fdc675df03bf.png)
