### ISSUE TITLE
Improve ThirdStats tab title

### ISSUE THREAD

**Issue by koobs** [devmount/third-stats#132]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

The present tab title is "E-mail Account Statistics".

![2020-11-11 12_59_23-E-Mail Account Statistics - Mozilla Thunderbird](https://user-images.githubusercontent.com/1011612/98757758-1bfc9680-23c5-11eb-808c-2813a5c9b47a.png)

I propose an improvement: `ThirdStats: <account name>`, where `<account name>` is the dynamic value for the currently selected account for which stats are displayed, for the following reasons:

 * The stats displayed at present are for a single account.  Tab title should reflect that (like browser tabs given a page <title>)
 * Branding in title
 * E-Mail vs Email (it bugs some people, me included), and it somewhat redundant (we're in our mail client), so remove it.
 * "Account" not valuable enough to be in title

Additionally suggest, setting the tab icon (if possible) to the ThirdStats logo.

Edit: I had originally proposed "ThirdStats Mail Statistics". After reconsideration, I updated the proposal to `ThirdStats: <account name>`.

* Includes ThirdStats name (branding), and
* Describes the (informational) contents of the tab, better (more accurately) than the present title
* I just realised that stats are for a single account, so the tab title should reflect that (like browser tabs given a page <title>)

**Describe alternatives you've considered**

 * Thunderbird Stats (per and matching the main dashboard text).
 * ThirdStats
 * ThirdStats Statistics
 * ThirdStats: All Accounts (I also like this, see considerations below)

**Additional context**

 * Consider if in the future there is a tab (dashboard) or option to view 'global' statistics, across accounts (see #92), The title should reflect that. Suggestion: "ThirdStats: All Accounts"

**Comment by devmount** [comment]
Hi @koobs, again thank you so much for your extremely detailed description 👏🏻👏🏻
I'm totally with you and implemented your suggestion on title and favicon:

![image](https://user-images.githubusercontent.com/5441654/99627662-04f91c80-2a35-11eb-918f-5e898ef9dd27.png)

**Comment by koobs** [comment]
> Hi @koobs, again thank you so much for your extremely detailed description 👏🏻👏🏻
> I'm totally with you and implemented your suggestion on title and favicon:

My pleasure, you're welcome :)

Thanks for resolving!

**Comment by koobs** [comment]
@devmount Does Thunderbird not currently at present support setting tab icons? 

Might be worth a bug report to request API support for it, like Firefox ([WebExtensions API: Tabs](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs/Tab))

Would you like me to create a separate issue in this repo for tracking the feature request?

**Comment by koobs** [comment]
> @devmount Does Thunderbird not currently at present support setting tab icons?


Mmm, looks like it may be supported ... ?

[Thunderbird WebExtensions: Tabs](https://thunderbird-webextensions.readthedocs.io/en/68/tabs.html#tab)

**Comment by devmount** [comment]
> Does Thunderbird not currently at present support setting tab icons?

It does, and I already implemented it (see screenshot above).

**Comment by koobs** [comment]
> 
> 
> > Does Thunderbird not currently at present support setting tab icons?
> 
> It does, and I already implemented it (see screenshot above).

Ugh, silly me :) Looks great.

Thanks Andreas!

**Comment by devmount** [comment]
No problem at all 😂
