### ISSUE TITLE
Utilize GitLocalize for translation management

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#135]
Hey there fellow contributors 👋🏻

Thanks to @marcelstoer's [suggestion](https://github.com/devmount/third-stats/issues/109#issuecomment-725690221), I imported this projects localizations to [GitLocalize](https://gitlocalize.com), a tool to make the collaboration on completing translations (hopefully) a lot easier than using GitHub issues. It basically tracks, if the translated files have all values from the source file (English translation) and provides the possibility to translate missing values and create PRs from it. That simple.

I wanna thank you all, for your engagement in this project so far and wanted to ask, if you would be willing to try this tool together with me (as I've never used it before) and see, if this simplifies things. If so, please do the following steps, that I can add you to the ThirdStats translation team:

1. Go to https://gitlocalize.com/repo/5505
2. Click the "Sign in with GitHub" Button in the upper right corner <br><img src="https://user-images.githubusercontent.com/5441654/99146621-23989580-267a-11eb-962e-3f7ef86cc8f5.png" width="80px" />
3. Give the necessary permission<br><img src="https://user-images.githubusercontent.com/5441654/99146634-44f98180-267a-11eb-8386-84561ca3cfdd.png" width="80px" />
4. Come back here and drop a quick answer to this post "I'm in" - I can then add you to the team

Thanks again for your contributions to ThirdStats - You are awesome 👏🏻! If you have any other/better ideas, please let us know below, that we can discuss it 👍🏻

(that this post gets attention, I mention everyone who has already contributed to localization: @altmas5 @Leos1113 @ajyan @martinsustek @roninJosue @SabrinaFZ @antoinevth @aurelienrouze @uveic @kunaljain0212 @mdfaizan7 @leobia @edmael @marcelstoer @dfoltynski @wikiyu @printf-ana @di3goCS @kerlon5 @maria-muravyova @FrejBjornsson @kerlos @tosbaha @jswildcards @Hsins)

**Comment by jswildcards** [comment]
@devmount I'm in

**Comment by FrejBjornsson** [comment]
@devmount I'm in! 😊

**Comment by devmount** [comment]
Wow, you're fast 👏🏻 @jswildcards I added you ✅ @FrejBjornsson I couldn't find you yet 🔍

**Comment by FrejBjornsson** [comment]
@devmount i must have missed something, i should show up now 👍

**Comment by di3goCS** [comment]
I'm in!

**Comment by leobia** [comment]
I'm in! 😀

**Comment by di3goCS** [comment]
I requested a review

**Comment by kerlon5** [comment]
I'm in (kerlon5)

**Comment by devmount** [comment]
> I requested a review

Awesome! I created PR #136 from it, it seems to work showing you as the author of the commit ✅
![image](https://user-images.githubusercontent.com/5441654/99151296-666a6580-269a-11eb-93e4-8fcda45ccf6f.png)

**Comment by marcelstoer** [comment]
Count me in.

**Comment by altmas5** [comment]
I'm in

**Comment by Hsins** [comment]
I'm in

**Comment by martinsustek** [comment]
I'm in

**Comment by aurelienrouze** [comment]
I'm in !

**Comment by mdfaizan7** [comment]
I'm in

**Comment by uveic** [comment]
I'm in.

**Comment by devmount** [comment]
Now that we used GitLocalize for more than two weeks: how do you like this tool? I think it's definitely better than GitHub issues as it provides a great overview of the current state of each translation. What I'm missing though is some kind of notification system, that you can get a hint if keys were added or the source language changed.

**Comment by marcelstoer** [comment]
> What I'm missing though is some kind of notification system, that you can get a hint if keys were added or the source language changed.

Same here. I can't be asked to head over to https://gitlocalize.com/repo/5505/ja/public/_locales/en/messages.json?filter=all&limit=50&offset=50 every week or so just to check whether there's work to do or not.

The other very important but missing feature is the option to filter (or sort) the content by missing keys. Our i10n resource is still small but even now I need scroll through two pages and visually identify the missing/invalid translations.

**Comment by devmount** [comment]
@marcelstoer Thank you for your feedback.

> The other very important but missing feature is the option to filter (or sort) the content by missing keys.

This feature actually exists:

![image](https://user-images.githubusercontent.com/5441654/100540199-267bb480-323c-11eb-935e-3d55730b7d5d.png)

or just got to https://gitlocalize.com/repo/5505/ja/public/_locales/en/messages.json?filter=untranslated

I'll check if I can automate notification with a corresponding GitHub Action, I'll let you know.

**Comment by marcelstoer** [comment]
Oh, I missed that filter icon, thanks.

**Comment by devmount** [comment]
Hey there, I hope everyone's fine! 🙏🏻 

Since we are on ThirdStats v1.6.0 for a while now, I just wanted to set a quick reminder to check for missing translations of your language on https://gitlocalize.com/repo/5505 ✅ 
Thank you for every little contribution and making ThirdStats more accessible around the world 👏🏻

**Comment by di3goCS** [comment]
Haha, new portuguese translate it's done!

**Comment by devmount** [comment]
@di3goCS Awesome, many thanks!

**Comment by devmount** [comment]
Many thanks to everyone so far! Thanks to you, ThirdStats is now fully translated in 7 languages 🤗

**Comment by devmount** [comment]
Hey everyone,

since I had some issues with Gitlocalize (not keeping json key order, wrong PR content overwriting existing translations etc), I decided to drop it and find an alternative. I will open a new thread as soon as I found something better. Stay tuned!

**Comment by devmount** [comment]
Aaaand here is the new thread: #343 

Thanks again for everyone contributing, no matter how much! 🤗
