### ISSUE TITLE
Add translation: Czech

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#14]
**Provide the name and the two-letter code of the new language**
Czech, `cs`

**Steps to add the translation**
- Add a folder `public/_locales/cs/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

**Comment by ajyan** [comment]
Hi, even if I'm not a native Czech speaker, would you be comfortable with me going to a translator and converting the `messages.json` file to Czech?

**Comment by devmount** [comment]
Hi Andrew, thank you for your contribution! By *translator*, do you mean a human or a machine? I actually prefer native speakers so I will wait a bit more too see whether a native will sign up for it. If not, I'll come back to your offer.
