### ISSUE TITLE
Reimplement exclusion/hiding of local account(s)

### ISSUE THREAD

**Issue by Eagle3386** [devmount/third-stats#151]
**Is your feature request related to a problem? Please describe.**
Commit #29 fixed #13, but also raised the issue of an empty option for those not using local folders, i. e. basically anyone relying on today's de-facto-standard, IMAP(S).

**Describe the solution you'd like**
Reimplement exclusion/hiding of local account(s), i. e. offer an option (preferably being enabled by default due to aforementioned reason(s)) to exclude any local account(s) from ThirdStats.

**Describe alternatives you've considered**
Unfortunately, there's none available. :(

**Additional context**
Maybe changing per-account stats to overall stats with different color per account & enabling each user to select which account(s) s/he wants to be measured, would be even better - I'll open another request for that. :)

**Comment by devmount** [comment]
Hi Martin, thanks for reporting this - you're right, the majority of people (including me) probably doesn't use local accounts. In a first step, I will implement a simple list of all existing accounts in the add-on options, where you can activate/deactivate any account. Local accounts will be deactivated by default. 

As you mentioned in #152, the next step is the implementation of the overall stats (I first have to think about what's the best way visualize that while keeping a clean UI), but this won't be part of the next release.

Thanks again for your thoughts!

**Comment by Eagle3386** [comment]
Sounds great, Andreas! 👏🏻🤩

Again, my pleasure regarding providing suggestions for improvement - the more (useful 😉) suggestions, the better the stats & let's be honest: mail hoarder like us love stats looking several years back, don't we? 😅🙈

**Comment by devmount** [comment]
> mail hoarder like us love stats looking several years back, don't we?

I see no way to disprove that 😅

**Comment by devmount** [comment]
@Eagle3386 This feature is now released. Please test it and issue a bug report, if something doesn't work as expected. Thank you!

**Comment by Eagle3386** [comment]
@devmount Already updated, but actually found a bug - will open an issue right after this comment..
Nonetheless, thanks again for this awesome project! 👏🏻🤜🏻

**Comment by devmount** [comment]
Ok thank you!
You're welcome - wouldn't be that awesome without people like you who test, provide feedback and file bug reports 🤛🏻👏🏻
