### ISSUE TITLE
Account selection toggles all items instead of only the clicked one

### ISSUE THREAD

**Issue by Eagle3386** [devmount/third-stats#165]
**Describe the bug**
Clicking an item within the newly introduced account selection list (#151) toggles all items instead of only the clicked one

**To Reproduce**
1. Go to ThirdStats's options dialog.
2. Click any account item.
3. All checkmarks are toggled.

**Expected behavior**
The clicked item's checkmark is toggled.

**System (please complete the following information):**
- Windows 10 Pro x64
- Thunderbird 84.0b2 x64

**Comment by devmount** [comment]
Thank you for reporting this. Can you please do the following:

- open the console (add-ons > gear > debug add-ons > scroll to ThirdStats > Inspect)
- clear console (small trash icon on the upper left)
- go to the ThirdStats options and toggle the accounts
- paste any occuring error message

And another check:

- open the storage inspector (add-ons > gear > debug add-ons > scroll to ThirdStats > Inspect > Storage tab)
- go to Extension Storage > click child item > click options key > expand the accounts array
- paste a screenshot of your stored options
![image](https://user-images.githubusercontent.com/5441654/101182095-f2463080-364d-11eb-92f1-753dfc374546.png)

**Comment by devmount** [comment]
Ok this is not a Thunderbird 84.* issue. I just tested it:
![third-stats_accounts_bug](https://user-images.githubusercontent.com/5441654/101183549-f2dfc680-364f-11eb-984d-5dc3a8ee17fb.gif)

**Comment by Eagle3386** [comment]
> Thank you for reporting this. Can you please do the following:

My pleasure, I guess.. 😅

>     * open the console (add-ons > gear > debug add-ons > scroll to ThirdStats > Inspect)
>     * clear console (small trash icon on the upper left)
>     * go to the ThirdStats options and toggle the accounts
>     * paste a screenshot of any occuring error messages

No single message appear, although all filtering was disabled, i. e. nothing was hidden. 🥺

> And another check:
>     * open the storage inspector (add-ons > gear > debug add-ons > scroll to ThirdStats > Inspect > Storage tab)
>     * go to Extension Storage > click child item > click options key > expand the accounts array
>     * paste a screenshot of your stored options
>       ![image](https://user-images.githubusercontent.com/5441654/101182095-f2463080-364d-11eb-92f1-753dfc374546.png)

Done, result looks like this (and yes, all accounts even the local one, was ticked prior to creating this screenshot 😞):
![image](https://user-images.githubusercontent.com/5111490/101289323-0334a480-37fc-11eb-9d9e-e5eddbcc7c8a.png)

> This might be a Thunderbird 84.* issue.

As stated by yourself later, i. e. right above this comment, it's not a Thunderbird issue. Please let me know if I can be of any further help! ;)

**Comment by devmount** [comment]
Thank you @Eagle3386 for these results. This looks like a mistake on my side. I released v1.0.2 to fix this, please update your ThirdStats (if it's not already done automatically by TB) and try again.

**Comment by Eagle3386** [comment]
Awesome, works like a charm now! 🥳

BTW, the release notes, too:
![image](https://user-images.githubusercontent.com/5111490/101369478-a8a55200-38a8-11eb-87c3-4f736348c8b3.png)

**Comment by devmount** [comment]
Great! And sorry for the inconvenience.
