### ISSUE TITLE
number axis for main statistics

### ISSUE THREAD

**Issue by kkalev** [devmount/third-stats#170]
When viewing the main statistics line chart It is rather inconvenient that a vertical number axis is not shown. That means that a screenshot of the chart for example cannot be used to communicate specific quantitative details apart from volume differences between different time periods.

See example:

![image](https://user-images.githubusercontent.com/2707736/101482323-3c395a00-395f-11eb-9ce6-12aead98f641.png)

**Comment by devmount** [comment]
Thank you for this request - I will make the vertical axis configurable in the add-on options in the next release.

**Comment by devmount** [comment]
This feature is implemented now and will soon be published with the next release:

![image](https://user-images.githubusercontent.com/5441654/102545384-74a30b80-40b6-11eb-8f36-ca813253ae9a.png)

Let me know if everything works as expected then.
