### ISSUE TITLE
Possibility to select certain periods of time within the statistics tab

### ISSUE THREAD

**Issue by dacemotion** [devmount/third-stats#179]
**Is your feature request related to a problem? Please describe.**
Right now the automatically selected period of time of the mailbox statistics starts from the first mail up to today.

**Describe the solution you'd like**
It would be great, if there could be any kind of a "select a certain time-span" - button. 
So one would be able to visualize only the period of time one is interested in. 
This time-span-selection-button could be placed in the top row next to the Account-selection button

**Describe alternatives you've considered**
There is none.

Thank You very much for this great looking and pretty good working thunderbird add-on!

**Comment by devmount** [comment]
Thank you for this feature request. This already was implemented with #161 and will be part of the next release coming this week 👍🏻 Let me know if it works for you.

**Comment by dacemotion** [comment]
It works perfectly - thank You a lot!
And just adding a little idea: What Do You think about using the actual date as a standard default setting for the end-date?

**Comment by devmount** [comment]
Awesome 👍🏻 
Very good idea - I'll wait for some more user feedback on this. If more people would like this, I will provide an add-on option where you can activate this default setting 👍🏻
