### ISSUE TITLE
How to see the stats?

### ISSUE THREAD

**Issue by scharf** [devmount/third-stats#180]
Can you quickly explain how to show the stats? It is not obvious from the descriptions?

**Comment by devmount** [comment]
Hi Michael,
thank you for this question. Once you installed the add-on, the ThirdStats button appears in the toolbar. Clicking it opens a popup menu, which allows you to open the stats page by clicking on the title or on a single account:

![image](https://user-images.githubusercontent.com/5441654/102816239-fb652a80-43cd-11eb-86ed-7aae79088031.png)

I'll try to make that more clear in the add-on description and readme - thanks again for pointing that out.

**Comment by scharf** [comment]
👍 

I simply did not see it, because I just updated thunderbird from  a really old version to `78` (the old version did not run on Mac Big Sur) and I did not realize this subtle change in the UI.

**Comment by scharf** [comment]
...especially, because I turned off labels:
![image](https://user-images.githubusercontent.com/3731059/102820976-76cada00-43d6-11eb-8bd4-22a27a5ed0c4.jpeg)

**Comment by devmount** [comment]
I see, I'll take this into account when updating the description 👍🏻

**Comment by devmount** [comment]
I updated readme and add-on description. Merry christmas 🎄🔔
