### ISSUE TITLE
use sqlite to speed up the stats

### ISSUE THREAD

**Issue by scharf** [devmount/third-stats#181]
I don't know much about thunderbird add-ons, but I have been using `SQLite` directly to get some simple stats on my thunderbird account. I have 640 folders, 480,000 emails, 20 accounts, and the oldest messages are from 1994. `third-stats` is very slow, but running `SQLite` queries is quite fast.

For example, running this query on `global-messages-db.sqlite` takes a few seconds. And I think if you iterate over the result, it should be quite easy to get the required statistics. 

```sql
select date, c3autho, folderURI
from
    messages, messagesText_content,folderLocations
where
    messages.id == messagesText_content.docid
    and messages.folderID == folderLocations.id
    and folderURI like 'mailbox://441585@mail.gmx.de%'
order by
    date
```

This allows for easy filtering (e.g, by author)

```sql
select count(*)
from
    messages, messagesText_content,folderLocations
where
    messages.id == messagesText_content.docid
    and messages.folderID == folderLocations.id
    and folderURI like 'mailbox://441585@mail.gmx.de%'
    and c3author like '%scharf@%'
```

I don't know if `SQLite` in thunderbird allows regex matching, which opens a lot of possibilities...

**Comment by devmount** [comment]
> I have 640 folders, 480,000 emails, 20 accounts, and the oldest messages are from 1994

Wow 😮 That's quite a lot 😅 But the processing finishes at some point? How long does that take? Are the 480k emails the total of all 20 accounts? How many emails does your largest account hold (as ThirdStats only does per account processing)?

This add-on is based on Thunderbirds WebExtension APIs which basically only provide two functions to retrieve and iterate over all emails ([list](https://thunderbird-webextensions.readthedocs.io/en/78/messages.html#list-folder) and [query](https://thunderbird-webextensions.readthedocs.io/en/78/messages.html#query-queryinfo)). As far as I can tell there is no possibility to run raw sql queries (for security reasons, I assume) so I can't improve performance at this point I'm afraid.

I placed [a corresponding topic at Thunderbirds topicbox](https://thunderbird.topicbox.com/groups/addons/Td78fd9d363f0f6ab/what-is-the-fastest-way-to-iterate-over-all-messages), let's see if someone has an idea.

For now, you will have to wait until ThirdStats processed your emails. If you haven't deactivated the cache, you'll be able to quickly switch between your accounts, once they got processed.

Thank you anyway for this great idea of executing direct sql queries. And sorry for the inconvenience.

**Comment by scharf** [comment]
My biggest account has 168k mails. It takes like 10 minutes.

It never finishes for some of the accounts. I see the basic stats and that's it. It seems that there are some broken mails, like mails without sender or senders that only contain a name but no email. There are also some mails without date.

It's unfortunate that WebExtension does not seem to provide access to `SQLite`. 

> And sorry for the inconvenience.

This is not an essential tool, it's just fun ;-) and this was not a bug report. It was just a developer thinking loud ;-)

**Comment by devmount** [comment]
> My biggest account has 168k mails. It takes like 10 minutes.

Hm, that's indeed very slow. My 31k account gets processed in 19s, which is ~1600mails/s. Your account only gets 280mails/s for some reason...

> It never finishes for some of the accounts

This may be this known issue: #19 

> This is not an essential tool, it's just fun ;-) and this was not a bug report. It was just a developer thinking loud ;-)

I see and I'm glad you see it that way - nevertheless ThirdStats does not exactly deliver what it promises and that's what I'm sorry for 🤷🏻‍♂️

**Comment by devmount** [comment]
Since you stated, that this is **not**  a bug report, are you nevertheless willing to analyze this further? If so, you could [create a profile](https://github.com/thunderbird-conversations/thunderbird-conversations/wiki/Profiling-Conversation's-Performance) of the processing of your largest email account. and provide a link to your results. That way, I can compare it with my own profile and may identify possible performance issues.

In the end, no API will be as performant as direct SQL queries, I'm afraid.

**Comment by devmount** [comment]
Please reopen this issue in case you created a performance profile. Thanks you!
