### ISSUE TITLE
Possibilities to: a) Select set of relevant accounts, b) select relevant periods, c) longer "most relevant" lists

### ISSUE THREAD

**Issue by drfedtke** [devmount/third-stats#182]
first of all, great work you did! this add-on is needed.

for a daily use, and maybe to review at christmas time with whom I had conversation with in the current year, it would we great to have the following:

a) a possible configuration which accounts should be included to the analysis
b) a possible configuration if a date-range, and a good default like "last nnn days"
c) the top-10 list should be extandable to top-100 or even more; actually you are interested in the "distinct" of your email conversation partners
d) maybe you can also make some statistics on email attachments

when this is possible, you definitely offer a powerful tool for everyday's usage.

then I also donate EUR 20,00.

best regards
stephen

**Comment by devmount** [comment]
Hi Stephen,
my pleasure, I'm glad this add-on is useful for you.

a) This is already implemented (#159). Just head over to the add-on options and configure the accounts list as you wish.
b) This is also already implemented (#173), but not released yet. I plan to release this tomorrow.
c) The `10` is currently hard-coded. I created another issue (#183) for this to implement a corresponding add-on option.
d) In which exact metric about attachments would you be interested in?

**Comment by devmount** [comment]
FYI c) now also got implemented with #206 and will be released soon.

**Comment by devmount** [comment]
I added #213 for d), please comment there if you have any ideas about attachment metrics.
