### ISSUE TITLE
Option to stop/change account

### ISSUE THREAD

**Issue by rfwolff** [devmount/third-stats#192]
It would be helpful to have the option to stop analysing an account or to select a different account. This would avoid having to close the tab with the add-on to analyse a different account.

**Comment by devmount** [comment]
The reason for the current behavior is, that only fully processed account data can be cached. Therefore the select field is disabled while processing.
I totally agree with you, that especially for large accounts it would be a good thing to be able to cancel processing. I will think about how to implement this.

In the meantime, you can use <kbd>F5</kbd> or right click anywhere > Reload to refresh the page and cancel current processing without closing the tab:
![image](https://user-images.githubusercontent.com/5441654/103214563-07427680-4911-11eb-9360-26f1a29477d7.png)

**Comment by rfwolff** [comment]
Good to know, thanks.

**Comment by devmount** [comment]
After doing some research, I didn't find a suitable solution to this. In case you really need it, please use the workaround provided in my previous post. For now, I will close this request, but If someone has a clever idea how to implement this processing termination, PRs are welcome and I'm happy to reopen it.
