### ISSUE TITLE
Selection of folders

### ISSUE THREAD

**Issue by rfwolff** [devmount/third-stats#194]
When selecting what to analyse, it would be nice to be able to select folder(s) of a certain account.

**Comment by devmount** [comment]
Actually this is already implemented. The filter area at the top right area of the stats page contains a drop down for a specific folder of the currently selected account. See #44 

![image](https://user-images.githubusercontent.com/5441654/103215262-22ae8100-4913-11eb-9905-6864c337a721.png)

Or did you mean something else?

**Comment by rfwolff** [comment]
My bad, I missed that.

**Comment by devmount** [comment]
No problem at all
