### ISSUE TITLE
Better integretation of add-on options within Thunderbird

### ISSUE THREAD

**Issue by rfwolff** [devmount/third-stats#195]
Options for this add-on can be found via "Add-ons Manager" / "ThirdStats" / Tab "Options".
It would be good to display these in "Tools" / "Add-on Options" as well.

**Comment by devmount** [comment]
Thank you for this suggestion. I'm totally with you, the add-on options should be more accessible. I'll see how new menu entries can be add without using legacy APIs.

**Comment by rfwolff** [comment]
Thanks for looking into that.

**Comment by devmount** [comment]
It's [currently not possible](https://thunderbird.topicbox.com/groups/addons/T77adb065b7855df2/add-entry-to-main-menu) to add entries to the main menu without using the lecacy menus API (which I don't want).

So for now, I will implement a gear icon in the popup menu as well as on the stats page to open the options page separately as a new tab.

**Comment by rfwolff** [comment]
Thanks for the update. Hopefully, it will be possible at some point. I like the idea of implementing a gear icon in the popup menu.

**Comment by devmount** [comment]
The popup menu and stats page now hold a gear icon link in the upper right corner to open options in a dedicated tab.
