### ISSUE TITLE
Add translation: Dutch

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#20]
**Provide the name and the two-letter code of the new language**
Dutch, `nl`

**Steps to add the translation**
- Add a folder `public/_locales/nl/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

**Comment by Rookie3109** [comment]
Hey could you assign this to me? I'd love to work on this for hacktoberfest :)

**Comment by devmount** [comment]
@Taneesha-creates Are you still up to this?

**Comment by devmount** [comment]
This issue isn't necessary anymore - see #135.
