### ISSUE TITLE
"All Account" statistics not available

### ISSUE THREAD

**Issue by dynobo** [devmount/third-stats#208]
**Describe the bug**

Hi @devmount, first, thanks you very much for implementing the [all-accounts stats feature](https://github.com/devmount/third-stats/pull/196)! :+1: 

It should be available in v1.2.0, right? I just updated to v1.2.0 but sadly, it doesn't work for me: 

**To Reproduce**
A) Steps to reproduce the behavior:
1. Go to Thunderbirds Stats by selecting an individual account
2. The "Account"-dropdown is missing the "All Acounts" option. 

B) Steps to reproduce the behavior:
1. If I click "Open all stats" on the button-modal instead going through an individual account
2. The loading spinner keeps running, but doesn't get to an end.
3. No stats are shown

**Screenshots**
![Screenshot from 2021-01-09 20-32-56](https://user-images.githubusercontent.com/11071876/104107260-2f3fbb80-52bb-11eb-9a69-d04c302b8409.png)

![Screenshot from 2021-01-09 20-35-07](https://user-images.githubusercontent.com/11071876/104107265-31097f00-52bb-11eb-9919-4d1283b9eac6.png)

![Screenshot from 2021-01-09 20-35-53](https://user-images.githubusercontent.com/11071876/104107269-349d0600-52bb-11eb-93c3-83add16a41e5.png)

**System (please complete the following information):**
- OS: Ubuntu 20.10
- Thunderbird Version 78.5.0 (64-bit)

**Additional context**
I don't know if it matters, but one of my accounts is an IMAP-Account, while the other one is a Local Account. The stats for the individual accounts are working fast and flawless.

**Comment by devmount** [comment]
Hi @dynobo,
thank you for reporting this.

A) The "All Accounts (Sum)" option only appears, if Cache is enabled (due to performance reasons) - please check the add-on options for this.

B) This is indeed a bug, if Cache is disabled (I missed that case at this point). I'll fix this asap!

**Comment by devmount** [comment]
(Sorry, closed this by mistake)

**Comment by dynobo** [comment]
Thanks, while it wasn't the cache option, it actually lead me into the right direction:
Cache was already activated, but one of the accounts wasn't "ticked" as active:
![image](https://user-images.githubusercontent.com/11071876/104128607-eba38b00-5368-11eb-9383-254f2060feff.png)

I didn't notice that, because like in the screenshots submitted earlier, I was perfectly able to select and view statistics for _both accounts_, despite one of them being disabled in the settings. This seem like inconsistent behavior here... However, after enabling both accounts, the "All accounts" option appeared and is working well.

So, while there still seem to be an issue/inconsistency with the "Active Accounts" preferences, my original issue is know solved :-)
Feel free to close this issue, or keep it open to track the inconsistency. Thanks again!

**Comment by devmount** [comment]
I see, that's indeed another bug you discovered here 😅 Normally, all non-local accounts are disabled by default in the add-on options. I'll take a look into this and close this issue when fixed. Thanks again 👍🏻

**Comment by devmount** [comment]
I fixed it now with #210. The issue you encountered affected all users, who have two accounts where one account is local. Account lists should be properly initiated now.
