### ISSUE TITLE
Add translation: Polish

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#21]
**Provide the name and the two-letter code of the new language**
Polish, `pl`

**Steps to add the translation**
- Add a folder `public/_locales/pl/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

**Comment by wikiyu** [comment]
Hey @devmount I`m trying to translate this awesome plugin but i have a problem with plurals. 
I`ll do everything i can, but please check out a problem with pl_PL plurals (and other issues with other languages) like in https://stackoverflow.com/questions/12121515/multiple-plural-forms-in-gettext 
If you want in future go into other method of translate plurals, please mention me, ill make it one more time :-)

**Comment by devmount** [comment]
Hi @wikiyu, many thanks for your contribution and pointing out the plural problem! I didn't know about that! Can you please issue [a bug report](https://github.com/devmount/third-stats/issues/new?template=bug_report.md) for the plural problem, as this includes other languages as well? We can discuss ideas and possible solutions for this problem there. This issue here will be closed with your PR. Thanks again!
