### ISSUE TITLE
Add aggregated folder view, see the distribution of emails in folders in time

### ISSUE THREAD

**Issue by amedranogil** [devmount/third-stats#228]
**Is your feature request related to a problem? Please describe.**
I need to report monthly my work ours per project. For this I typically look at my calendar, but this feels short, It would be great if I could see the distribution of emails in my account folders for the last month(s). This way I can see where I have been spending most of my email time, as I use the zero inbox method and archive emails in project folder.

**Describe the solution you'd like**
Either 
1. a custom time selection, where I can select the begin/end and then see a pie chart (or Sunburst chart also representing sub-folders) distribution of emails in folders
2. a timeline with stacked area graph, where the areas represent the number of emails in each folder in time.

**Describe alternatives you've considered**
I tried [ThunderStats!](https://github.com/micz/ThunderStats), however the folder distribution is only available for "today" and "yesterday". It has a custom time selection, however it does not show this statistic (the statistics shown in this custom view are not very useful).

[this tool](https://aliquote.org/post/statistics-mu4e) might produce exactly what I need. However I am not proficient in this mu tool, nor the other commandline tools.

**Additional context**

**Comment by devmount** [comment]
Thank you for this feature request. Adding some aggregated folder stats is a great idea - the current Date Range filter is already capable of doing the time selection, so this is essentially implementing a pie/doughnut chart showing the folder message count distribution of the current date range. Won't be in the next release, but maybe in the one after.

**Comment by devmount** [comment]
This is now implemented and will be part of the next release.

Sneak Peek:
![image](https://user-images.githubusercontent.com/5441654/107869001-b9b2a680-6e89-11eb-8db0-1578284fc85f.png)
