### ISSUE TITLE
Add translation: Catalan

### ISSUE THREAD

**Issue by altmas5** [devmount/third-stats#23]
**Provide the name and the two-letter code of the new language**
Catalan, `ca`

**Steps to add the translation**
- Add a folder named like the two-letter code of the language you want to add under `public/_locales/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

I can add this translation

**Comment by devmount** [comment]
Awesome, thank you for this suggestion! I assigned this issue to you.
