### ISSUE TITLE
Screen resolution: Email addresses cut off

### ISSUE THREAD

**Issue by rfwolff** [devmount/third-stats#232]
Depending on the screen resolution, graphs/ tables are ordered/displayed differently (presumably to fit the available space) thus causing long email addresses to be cut at different lenghts.

In all tested screen resolutions, rows 1 and 2 display the counts (mails total etc.) and the activity graphs (Y/Q/M/Q and activity in 2021), respectively.

1. 1680x1050 - Two more rows displayed. Third row: graphs for Daytime, Weekday, Month; Fourth row: Temporal distribution, Most received from, Most sent to.
2. 2560x1440 - Only one more row, displaying graphs for Daytime, Weekday, Month, Temporal distribution, Most received from, Most sent to.
3. 1080x1920 - Three more rows displayed. Third row: graphs for Daytime, Weekday; Fourth row: graph for Month, Temporal distribution; Fifth row: Most received from, Most sent to.

In all of the resolution, longer email addresses (listed in either Most received from or Most sent to) are cut off, at around 44 characters (resolution 1), 32 characters (resolution 2), and 41 characters (resolution 3).

Possible solution: Make "widgets" (i.e. little unit displaying a graph or list of addresses) scalable so that view can be adjusted.

**Comment by devmount** [comment]
Thank you for this detailed report 👏🏻

I already revamped the stats page layout with #231 (organizing all charts in tab groups) and now improved responsiveness even more with #238. That means:

- Resolution 1 should now show all characters as this is now a one column view
- Resolution 2 should now show a lot more characters too (I only tested up to 50 characters)
- Resolution 3 still shows around 42 characters (depending on the character width)

I will not further optimize this as you can always see the full email address in the corresponding tooltip. Implementing resizable widgets will be high effort for little benefit. I hope this is ok for you.

You can download the latest build here, if you can't wait for the next release:
https://third-stats.cdn.devmount.com/
