### ISSUE TITLE
Export of results

### ISSUE THREAD

**Issue by rfwolff** [devmount/third-stats#233]
It would be nice to enable exporting of results, e.g. as csv file.

**Comment by koobs** [comment]
@rfwolff  Hi! Can ask for any insights on the motivation / use-case for this functionality? It might elucidate some additional features/behaviours for ThirdStats down the line.

 * Are you trying to take snapshots or see changes over time? 
 * Are you looking for raw data in the export (csv) or just the aggregated/calculated values? 
  * What fields are you interested in / should be in the csv?
  * If raw data, are you planning to use the data in a different tool, or to run your own analysis on them (in excel or whatever) ?

**Comment by devmount** [comment]
@rfwolff A simple way to implement this would be to just provide the processed data as JSON file to download. If you need a CSV file I would love to hear your opinion on @koobs's [questions](https://github.com/devmount/third-stats/issues/233#issuecomment-772289350), especially what structure (columns) this CSV file should have.

**Comment by ramonrrp** [comment]
I guess i'll be a useful feature to use data in other purposes.

I'm controlling two or three mail groups in my company, and a feature to export data generated from the app would help my weekly and monthly reports

**Comment by koobs** [comment]
@ramonrrp What questions would be handy for a data export to answer?

 * Recipients / Senders by mail count?
 * Total number of messages per week / month?
 * ...

**Comment by rfwolff** [comment]
> @rfwolff Hi! Can ask for any insights on the motivation / use-case for this functionality? It might elucidate some additional features/behaviours for ThirdStats down the line.
> 
> * Are you trying to take snapshots or see changes over time?
> * Are you looking for raw data in the export (csv) or just the aggregated/calculated values?
> * What fields are you interested in / should be in the csv?
> * If raw data, are you planning to use the data in a different tool, or to run your own analysis on them (in excel or whatever) ?

@koobs - Apologies for the late response.

Regarding your questions:
- I was thinking of snapshots. However, I do end of year/ end of quarter reviews with data being collated in an Excel sheet. Potentially, this could be replaced by a ThirdStats output that would cover changes over time.
- Currently, I am using the aggregated/calculated values. While not a priority, I could see the use of looking at the raw data myself (see fourth bullet point).
- Everything that is used to create the graphs/figures as well as table outputs in ThirdStats, e.g. from, to, time sent, account etc.
- I am not doing that at the moment, however, I would be interested to have the raw data so that I can run my own analyses, likely in Excel or R. However, this is not a priority for me as the aggregated data are covering most of what I am interested in.

**Comment by ramonrrp** [comment]
> @ramonrrp What questions would be handy for a data export to answer?
> 
> * Recipients / Senders by mail count?
> * Total number of messages per week / month?
> * ...

 Maybe a kind of export of the raw data, to contribute in another analysiss apps, like powerBI and excel
Other point is the possibility to export the graphs the way they are shown (i think they are really beautiful) with day/week/month and per user/group filters in a .png extension, for example.

**Comment by devmount** [comment]
> Maybe a kind of export of the raw data, to contribute in another analysiss apps

Just to clarify: "raw data" would simply mean a list of all email headers - that's what ThirdStats is processing. This would be a table like this:

| author | date | folder | account | read | recipients | ccList | bccList |
|--------|------|--------|---------|------|------------|--------|---------|
|        |      |        |         |      |            |        |         |
|        |      |        |         |      |            |        |         |
|        |      |        |         |      |            |        |         |

I think in a first step, I'll implement the json export of the currently processed/aggregated/displayed data. That means, you can also export filtered output (folder and date range). Once this landed, we can discuss if further export options are reasonable.

> Other point is the possibility to export the graphs the way they are shown

This can already be achieved by any screen snipping tool. Charts are generated by the Chart.js lib, I can check, if high resolution exports of these charts is somehow possible. If that is a feature you would like, please issue a separate feature request for that.

**Comment by devmount** [comment]
JSON export is now implemented with #255. If you need any further export formats, create a new feature request providing a detailed description of the data structure and format, that's needed.

**Comment by koobs** [comment]
@devmount How trivial would a "right-click" context menu item for graphs be to "Save" them, rather than a full blown or separate "export function" ?

**Comment by devmount** [comment]
The ThirdStats charts are created using Chart.js, which draws the charts to an HTML canvas. I guess the most easy way would be to just convert this canvas to a data url, encode it and use it as image source. I'm not sure it works that easy but if you need this, create a feature request and I'll see what I can do.
