### ISSUE TITLE
Toggling Dark Mode does not change theme in an open ThirdStats dashboard

### ISSUE THREAD

**Issue by koobs** [devmount/third-stats#236]
**Describe the bug**
--

When toggling ```dark mode``` (On or Off) while a ThirdStats dashboard tab is open, the theme for Options changes, but the theme in the open ThirdStats dashboard does not.

**To Reproduce**
--

1. Open ThirdStats Dashboard tab
2. Click `Options` in open dashbord tab
3. Toggle `Dark Mode` On or Off in `Appearance & Experience` section

**Expected behavior**
--

 * Options theme changes
 * Dashboard theme changes

**Actual Behaviour**
--

 * Options theme changes
 * Dashboard theme does not change

**System (please complete the following information):**
--

 * OS: Windows 10 Pro (20H2) Build 19042.746
 * Thunderbird Version: Daily (87.0a1 (2021-01-30) (64-bit)

**Additional context**

**Comment by koobs** [comment]
Just noted the following at the bottom on the Options page:

```
. If the stats page is already open, you have to reopen or reload it for changes to be applied
```

If changing the theme in open tabs is a Thunderbird limitation, it may be worth adding these notes in ℹ️ style help markers on each relevent/affected option inline

**Comment by devmount** [comment]
Thank you for reporting this. I didn't implement event listeners for option changes yet, but especially for the options in the 'Appearance & Experience' section this would totally make sense.

> If changing the theme in open tabs is a Thunderbird limitation, it may be worth adding these notes in ℹ️ style help markers on each relevent/affected option inline

Awesome idea, will do this 👍🏻

**Comment by devmount** [comment]
This is now implemented and will be part of the next release. FYI: Changes of *Dark mode*, *Vertical axis*, *Start of Week* and the account colors are directly applied. All other options need a window or cache refresh. Options now have a hint symbol with a tooltip that indicates, whether the stats page or the cache has do be reloaded after changing the options value.

**Comment by koobs** [comment]
❤️
