### ISSUE TITLE
Add Reset Options option to Options

### ISSUE THREAD

**Issue by koobs** [devmount/third-stats#237]
**Is your feature request related to a problem? Please describe.**
--

As a user, it is difficult to remember what the default options of a program are, or what changes we have made. This can create problems when trying to identify or isolate issues in a local configuration, and make debugging/isolating for upstream (you) more challenging.

**Describe the solution you'd like**
--

Add a `Reset Options` button in an appropriate place (suggest: bottom of options page, or top of Options page inline with Options header, right-aligned, see screenshot), that resets settings to the default settings.

**Describe alternatives you've considered**
--

None

**Additional context**
--

 * If reloading open tabs or the Options page is necessary to reflect resetting options values (in Options UI control states), either reload the relevent tabs for the user, or present an Option (ideally) or Message (at minimum) for the user to manually action.

**Screenshot**
--

![2021-01-31 13_36_34-ThirdStats_ Options - Thunderbird Daily](https://user-images.githubusercontent.com/1011612/106373111-4b8cc080-636e-11eb-9eb9-444fdd9c024d.png)

**Comment by devmount** [comment]
Totally with you. I think this option best fits under ''Storage & Cache'.
