### ISSUE TITLE
Not Processing Emails In Trash or Spam Folder

### ISSUE THREAD

**Issue by DarkArc** [devmount/third-stats#242]
**Describe the bug**
I wanted to process my Spam & Trash folders for my Gmail so that I could see where most of the emails I'm deleting are coming from. However, Thunderbird Stats shows no results for these folders.

**To Reproduce**
1. View stats for an account with emails in its Trash or Spam folders
2. Select the Trash folder filter

**Expected behavior**
The stats page updates with data about the emails in the trash folder.

**System (please complete the following information):**
- OS: Fedora 33
- Thunderbird Version: 78.7.0 (64-bit)

----

EDIT: Looks like this might apply to any folder that isn't stored for offline use or is stored for offline use, but actively downloading.

**Comment by devmount** [comment]
Thank you for reporting this. You can try the following: Do a right click on the affected folder, click *Properties* and make sure that "include messages in global search result" is checked.

![image](https://user-images.githubusercontent.com/5441654/106953687-f61c2f00-6732-11eb-978b-07766f49d7c3.png)

Does this change anything for deleted messages?

ThirdStats is using TBs WebExtensions APIs to query all messages and I didn't find a way to query junk messages yet. I already placed a [corresponding question at TBs topicbox](https://thunderbird.topicbox.com/groups/addons/T4aef9dcece8deb48/how-to-query-messages-with-junk-information).

**Comment by DarkArc** [comment]
Interestingly, don't have that checkbox

**Comment by devmount** [comment]
Really? Well that's interesting indeed... I've tested this on Manjaro and the dialog is the same as on Windows. Can you share a screenshot of your folder properties dialog?

**Comment by DarkArc** [comment]
![Folder Properties](https://user-images.githubusercontent.com/778012/107069975-ada35680-67b0-11eb-9121-39c464a8124a.png)
Yup

**Comment by devmount** [comment]
Ok, for the deleted messages: Please reach out to the Thunderbird support and get to know, why the global search option and if it's possible to activate global search for folders e.g. directly in the TB config.
For the spam/junk messages: [I asked this](https://thunderbird.topicbox.com/groups/addons/T4aef9dcece8deb48/how-to-query-messages-with-junk-information) in TBs topicbox and it seems like a bug. We'd have to wait for a fix to query junk messages.

**Comment by devmount** [comment]
Since the last release 1.6.0 of ThirdStats, it's now possible to query the junk and trash folders too. I reimplemented the message retrieval to avoid the Thunderbird issue. Can you confirm that it's working now?

**Comment by DarkArc** [comment]
Hey thanks, seems to be working great now :)

**Comment by devmount** [comment]
Awesome!
