### ISSUE TITLE
Display (in progress) mail counts while processing

### ISSUE THREAD

**Issue by koobs** [devmount/third-stats#248]
Is your feature request related to a problem? Please describe.
--

During processing (initial run, on refresh, after clearing cache), all mail metrics/counts remain 0 until processing is complete (see screenshot below). Live (processing) counts would provide some entertainment value to the user while they wait, and may also prevent confusion ("why are the counts zero??"), if they don't notice the current minimal progress mechanism.

Describe the solution you'd like
---

If possible, it would be lovely to see the counts accumulate (go up) up as processing happens. It also serves as a form of 'progress meter', where the only present progress UI element is a thin blue line under the toolbar of the main Thunderbird window.

Describe alternatives you've considered
--

None, this is an improvement suggestion, rather than a new feature.

Screenshot
---

![2021-02-09 12_22_13-ThirdStats_ koobs@FreeBSD org - Thunderbird Daily](https://user-images.githubusercontent.com/1011612/107302770-cc863f00-6a75-11eb-9086-371070922b5b.png)

**Comment by devmount** [comment]
Thank you for this feature request. This was already implemented in earlier versions of ThirdStats, but I decided against it since the accumulation of the numbers wasn't very smooth due to Thunderbirds single-process nature.

As soon as Thunderbird becomes multi-process (which it does from version 86 if I remember correctly), processing will be completely happen automatically in a background progress (making the need for a manual refresh button obsolete). I will then implement this and it will hopefully be a lot smoother. 🙏🏻

**Comment by koobs** [comment]
@devmount Not that I'm running Daily (which has e10s enabled), and it recently landed in Beta too [1]

If you want to gate the code around those versions (maybe just starting with daily), we might be able to get ahead of the release curve (picking up any other multiprocess issues in the meantime). I'm going to be staying on Daily and can test for you.

[1] http://forums.mozillazine.org/viewtopic.php?f=29&t=3070087

**Comment by devmount** [comment]
Thank you for these information, and thanks a lot for testing ThirdStats on the daily build - this is a great help 👏🏻
Ah yes, I'm already CCd to this bug 😅

**Comment by devmount** [comment]
@koobs Btw, you can hover over the thin blue progress bar to see a percentage - at least 😉

**Comment by koobs** [comment]
@devmount Happy to test any time if you want to produce an xpi out of a e10s-test branch or something (P.S I wish this cannot update extension TB bug would go away)

**Comment by devmount** [comment]
@koobs This is now implemented with #368 and will be part of the next release. It is enabled by default and can be disabled in the add-on options.

**Comment by koobs** [comment]
You're alive! YAY

Thank you so much :)

Let me know if you'd like me to return to annoying you with more suggestions ;)

**Comment by devmount** [comment]
There has been a lot going on the last few months (crazy times we live in). So unfortunately ThirdStats got much less attention than I would have liked.

Anyway, your "annoying" suggestions are always welcome here 🤗

**Comment by devmount** [comment]
If you have the time, it would be awesome if you could test [the latest build](https://third-stats.cdn.devmount.com/) and close or comment this issue accordingly.

**Comment by koobs** [comment]
I had planned to on the day but thunderbird is not showing me updates for extensions

**Comment by devmount** [comment]
Can you explain this in detail? Normally, you only need to install the XPI file manually (Settings > Add-ons and Themes > Extensions > Gear Button > Install Add-on from file > Choose the downloaded XPI file).

![image](https://user-images.githubusercontent.com/5441654/158936290-fd8e6709-78a9-40dd-9a5a-720bd1a40b44.png)

**Comment by koobs** [comment]
I still don't get any updates displayed when checking in thunderbird, so I'll need to test manually (with github release xpi)

**Comment by koobs** [comment]
Tested 1.8.0 (from github) with Thunderbird Daily 100.0a1 (2022-04-01) (64-bit)

I couldn't see 'Live Count' in preferences, but I tested nevertheless in the event it was just a prefs display issue, with:

- Reset options
- Cache enabled/disabled

Still the same animated blue progress bar, with counts remaining at 0 until completion.

I'll test latest 1.9a from dev site next.

![sshot-2022-04-04-11-11-14](https://user-images.githubusercontent.com/1011612/161458577-e85b57ea-637b-43ef-9075-b36456c88293.png)

![sshot-2022-04-04-11-11-21](https://user-images.githubusercontent.com/1011612/161458580-b71788df-4672-4370-9b2f-f79866846fc5.png)

**Comment by koobs** [comment]
Tested third-stats_v1.9-alpha.1648105994.

✅ Live count broadly functions nice work!

Issues:


- [ ] Mails unread `% of received` seems to update **once**, but not again until completion
- [ ] Mails received `% of total` is always 100% until completion (value is then updated to correct value)
- [ ] Mails send `% of total` is always 0% until completion (value is then updated to correct value)
- [ ] Mails starred is always 0 until completion. 

This may be a consequence of fetching email types in batches. If there's a method to fetch mails by reverse date, this may be better and provide other email types and counts interspersed. 

  - [ ] Mails starred `mails tagged` is always 0, even after completion. P.S I don't use tags, but ...

User thoughts:

What is mails **tagged** and how is it different from mails **starred**? Is this suppose to be, or would this better be `starred over total` ? `mails tagged` is confusing as it provides no context for what it is (at least to me) - Are 'tags' referring to TB's tags system like work/personal? 'tagged' is a little ambiguous if so, because 'tagged' can mean 'marked'.

Also, 'starred' metric is being overloaded (combined with) with 'tag' counts'. Why are they together? Are we treating starred as a 'tag' type ?  Maybe 'starred' metric would be better off in as 'Email Types' where you can include many unrelated types like:

 - starred
 - tagged
 - has:attachment
 - is:junk
 - priority
 - watched threads
 -  etc

But then we're starting to overload everything into/as a 'type'. Unread, read, sent, received are all arguably types (attributes of) of mail too.

In the short term, I would keep all metrics/types separate, as this is explicit and obvious. We can talk about how we might add more metrics (all currently a single line) in a separate issue, but i dont think this is a problem given you are automatically collapsing the grid at breakpoints. PS There's a minor issue for  'spam emails' at a certain size/breakpoint. Looks like there's no minimum width.

![sshot-2022-04-04-11-36-41](https://user-images.githubusercontent.com/1011612/161460156-09290ba5-cfeb-43fe-9042-4b3f2a89db43.png)

**Comment by devmount** [comment]
> I still don't get any updates displayed when checking in thunderbird, so I'll need to test manually (with github release xpi)

Do you mean add-on updates for ThirdStats? Testing manually with GitHub Release XPI is currently the only way as Thunderbird only provide updates that are pushed to ATN. Or did I miss sth here?

> Tested 1.8.0 (from github) with Thunderbird Daily 100.0a1 (2022-04-01) (64-bit)
> I couldn't see 'Live Count'

This is expected, Live Count is only available since version 1.9.x

**Comment by devmount** [comment]
> Tested third-stats_v1.9-alpha.1648105994.

Awesome, many thanks for taking the time 😍 

As you already guessed: The first 4 issues you mentioned are the result of the messages query method, the web extension APIs provide. Messages are retrieved in batches per folder, so unfortunately I can't change that without significant performance loss.

> What is mails **tagged** and how is it different from mails **starred**?

Tagged messages are those that got a tag from TB's tag system, starred messages are those that got marked with a star:

![image](https://user-images.githubusercontent.com/5441654/161618663-09bc405d-8a43-4a25-ba2b-988b824e5f7c.png)

I tried to use the terms already in use by TB, but you are right, things got a little mixed up here. I agree with you to keep all metrics separate, I thought about conditionally showing them (e.g. don't show the number of messages with tags at all, if there are no tagged messages). What do you think?

> We can talk about how we might add more metrics (all currently a single line) in a separate issue

Can you open a new issue for this? That would be great!

>  Looks like there's no minimum width.

Good catch, will fix this.

Thanks again and again for your thoughts, ideas and suggestions!

**Comment by koobs** [comment]
> Awesome, many thanks for taking the time 😍

Pleasure!

> As you already guessed: The first 4 issues you mentioned are the result of the messages query method, the web extension APIs provide. Messages are retrieved in batches per folder, so unfortunately I can't change that without significant performance loss.

On a related note, I noticed some main UI latency while stats were re-processing. I believe we've talked about back-grounded  (off main thread) processing in previous discussions. What's the current state of how ThirdStats does this and what methods TB provides to do things OMT, if any? If there's room for improvement, let me know and I'll create a separate issue to track.
> 
> > What is mails **tagged** and how is it different from mails **starred**?
> > ... <snip> ...
> I tried to use the terms already in use by TB, but you are right, things got a little mixed up here. I agree with you to keep all metrics separate, I thought about conditionally showing them (e.g. don't show the number of messages with tags at all, if there are no tagged messages). What do you think?

On one hand, not showing stats for those that have no data (0) makes sense, on the other, its valueable for users to see features that they aren't using yet, but may want to (feature discovery).

Thoughts:

If ThirdStats is likely to grow support for more mail attributes/types over time (and there's heaps!), and more of these are likely to only be used by certain users, and not others, it may be worth 'bundling' all types that are/have zero counts ('feature not in use') and creating a single box/metric for those like

**Empty Stats**
Tags: 0
Starred: 0
... : 0

> > We can talk about how we might add more metrics (all currently a single line) in a separate issue
> 
> Can you open a new issue for this? That would be great!

Will do.

**Comment by devmount** [comment]
> On a related note, I noticed some main UI latency...

Yes, I noticed this too. The docs still show the same recommended algorithm to retrieve all messages as it does for TB78. I created [a thread in TB's topicbox](https://thunderbird.topicbox.com/groups/addons/Tff4347c72fc99bbe/performance-of-message-retrieval) to see if there are possibilities to improve the algorithm taking e10s/multithreading into account. So yes, if you could create another ticket for this topic, this would be great!

> Thoughts: ...

Thanks a lot for your valuable thoughts! I think this topic better fits in the corresponding issue you offered to create about a flexible/extendable layout for the featured stats numbers on top.

**Comment by koobs** [comment]
I didn't look at the current implementation and there may be limited, if any, ways to improve performance without core Thunderbird implementation improvements, but I came across this Thunderbird messageList API snippet that may be worth comparing ThirdStats against, particularly in the async department: 

https://stackoverflow.com/a/60246205

**Comment by devmount** [comment]
Thank you, I will take a look into this! I think this issue here is now finished.
