### ISSUE TITLE
Questions about privacy and security

### ISSUE THREAD

**Issue by bachmannn** [devmount/third-stats#249]
1. Is the extension fully contained or does it request any data like (js packages) from third-party CDN servers?
2. Is it snowden-level privacy friendly or does it collect and sell your data?
3. What exactly are all the permissions used for.
4. Does it run as a web server with an open port which would expose it to vulnerabilities

**Comment by devmount** [comment]
Thank you for these awesome questions.

1. The extension is fully contained. All [dependencies](https://github.com/devmount/third-stats/network/dependencies) are retrieved and minified on build. No CDN is contacted during installation or runtime or ever on your side. You can verify that by opening the network tab in the dev tools and browsing ThirdStats.
2. What exactly is the definition of snowden-level privacy? ThirdStats does store the processed stats data in Thunderbirds extension storage for perfomance reasons. I called it the ThirdStats cache and you can clear and disable it in the add-on options, if you don't want that. As long as I am in my right mind, **none of my OS projects will ever sell user data**!
3. ThirdStats needs 4 permissions to work:
    - `accountsRead`: To iterate over all messages in all folders of you TB accounts to count and process them
    - `messagesRead`: To read the message header and retrieve the following information from it: *author*, *bccList*, *ccList*, *date*, *read*, *recipients*
    - `tabs`: To open the stats page and the options page in a new tab
    - `storage`: To save processed data in Thunderbirds extension storage.
4. No. It only runs locally. You can check the [build files](https://third-stats.cdn.devmount.com/) yourself by renaming `.xpi` to `.zip`, unzip it and browse the files.

A final word: This is a statistics add-on, so it obviously needs access to your messages to retrieve and process data to display it. I do my best to keep privacy at the highest possible level. If you ever find any vulnerability or security issue, please report it or even better provide a PR for it.

**Comment by bachmannn** [comment]
>     2\. does store the processed stats data in Thunderbirds extension storage for perfomance reasons
It only stores data locally, does not upload it to any server correct?

🚀 probably one of the best looking Thunderbird extensions in whole entire add-on store 🚀

**Comment by devmount** [comment]
> It only stores data locally, does not upload it to any server correct?

💯 correct! It's Thunderbirds local storage that's reserved for extensions.

> 🚀 probably one of the best looking Thunderbird extensions in whole entire add-on store 🚀

So glad you like it so much 😊 Mind [giving ThirdStats a review](https://addons.thunderbird.net/en-US/thunderbird/addon/thirdstats/#reviews) on ATN? Only if you like, don't feel pushed or something.

Thanks again for your security concerns!
