### ISSUE TITLE
ThirdStats public statistics

### ISSUE THREAD

**Issue by ovari** [devmount/third-stats#259]
Hi Andreas,

Can you please enable the ThirdStats' statistics to be public?

https://addons.thunderbird.net/en-US/thunderbird/addon/thirdstats/statistics/

What do you think?

Thank you

Óvári

P.S. Our email might be in your Spam/Junk folder

**Comment by devmount** [comment]
Hi Óvári,
what do you need these statistics for?

**Comment by ovari** [comment]
It would be nice to see how having a Hungarian translation improves the uptake of your add-on among Hungarians.

Please advise if there a reason to not make the statistics public.

Thank you

**Comment by devmount** [comment]
No there is no reason to not make the stats public, I just was curious about how you want to use them.

I made the stats publicly viewable now 📈 You can find them here:
https://addons.thunderbird.net/thunderbird/addon/thirdstats/statistics/usage/

For reference: https://twitter.com/devmount/status/1363731294027472897

Thanks again for translating ThirdStats into the Hungarian language 👏🏻
