### ISSUE TITLE
Right-click showing inappropriate menu items

### ISSUE THREAD

**Issue by ovari** [devmount/third-stats#260]
**Describe the bug**
Right-click on the display shows a context menu with options that are not appropriate. Seems to be from other add-ons, such as [ImportExportTools NG](https://addons.thunderbird.net/thunderbird/addon/importexporttools-ng/) by @cleidigh and [Simple Mail Redirection](https://addons.thunderbird.net/thunderbird/addon/simple-mail-redirection/) by Günter Gersdorf.

Aside: strange that the time is a negative number of seconds ago.

**To Reproduce**
1. Install some add-ons, say the ones listed in the `description` above
2. Open the Thirdstats tab
3. Right-click

**Expected behavior**
Only show contextual menu if there are appropriate options.

**Screenshots**
![image](https://user-images.githubusercontent.com/17465872/108587500-f447a200-73a7-11eb-8696-494963537bdc.png)

**System (please complete the following information):**
- OS: [Linux Mint 20.1 Cinnamon](https://linuxmint.com/)
- [Thunderbird Version 78.7.1 (64-bit) flatpak from Flathub](https://flathub.org/apps/details/org.mozilla.Thunderbird)

**Additional context**
Thank you

**Comment by devmount** [comment]
Hi Óvári,

thank you for reporting this. This is the general context menu of Thunderbird, so of course it's showing menu entries of installed add-ons who added their own. I won't disable the context menu, as the refresh button comes in handy sometimes.

> Aside: strange that the time is a negative number of seconds ago.

There is clearly something wrong in this screenshot of yours - it doesn't even show the stats numbers at all. If the processing doesn't work as expected, please issue a bug report. Thanks!

**Comment by ovari** [comment]
@cleidigh can you please fix the ImportExportTools NG add-on? Thank you

**Comment by cleidigh** [comment]
I could use some more information, but I'm not seeing what the issue is?

**Comment by ovari** [comment]
> I could use some more information, but I'm not seeing what the issue is?

1. Install [ThirdStats](https://addons.thunderbird.net/thunderbird/addon/thirdstats/)
2. Open ThirdStats tab
3. Right-click and items from [ImportExportTools NG](https://addons.thunderbird.net/thunderbird/addon/importexporttools-ng/) show in the ThirdStats tab, when they should not.

@cleidigh do you see what this issue is?

Thank you

**Comment by devmount** [comment]
As I already said: This is the general context menu of Thunderbird. I don't think @cleidigh can and will do something against these menu entries showing up in context of other extensions.

Personally I don't see an issue here, as you can simply ignore these entries or don't use the context menu in ThirdStats at all. 🤷🏻

**Comment by nkgm-bs** [comment]
When add-on developers add an item to context menus they can define where their item should be shown. Unfortunately the set of options is predefined and very limited, so in my case (Simple Mail Redirection) i have to use some kind of 'show everywhere'.

**Comment by cleidigh** [comment]
@ovari 
after reading all of the new comments I think I now understand.
@devmount  's looks like it provides access to the main Thunderbird message context Menu
on its custom statistics. page.  (@devmount please correct me if I'm wrong)   while his
extension adds items, so does import export toolsNG along with others.  none of our extensions attempt to modify other extensions menu additions. as others have commented this is just one of the scenarios that can happen when extensions have practically unlimited abilities to change the UI.  while it might not be perfect, my interpretation is that each extension is operating as designed .   please comment if we all agree so we can close this.
@cleidigh

**Comment by devmount** [comment]
@cleidigh agreed.

**Comment by ovari** [comment]
Does a bug report need to be opened for Thunderbird core so that add-on can be more specific where they can add context menus, instead of  'show everywhere'?

**Comment by devmount** [comment]
You are very welcome to do that 👍🏻

**Comment by nkgm-bs** [comment]
See
https://thunderbird.topicbox.com/groups/addons/T4fcfd415a3dba933/how-to-restrict-menu-items-to-message-display
and
https://bugzilla.mozilla.org/show_bug.cgi?id=1628087
