### ISSUE TITLE
Review and document ThirdStats Thunderbird permission requirements

### ISSUE THREAD

**Issue by koobs** [devmount/third-stats#268]
**Is your feature request related to a problem? Please describe.**

Privacy is important. Third-party extensions (code) running in a user context with important and sensitive data available (such as emails, which may include other sensitive information, such as passwords and PPI), should use principles of least privilege, and in the context of ThirdStats and Thunderbird, only use permissions that are *necessary* to provide the functionality desired by the user, and where possible, use *optional* permissions that can be enabled on a per-feature level.

Installing or updating ThirdStats, permissions confirmation dialogs do not always by themselves adequately explain the need for particular permissions (though some may be obvious). Even as a technical user, it was not immediately obvious, for example, why the 'Download files or modify download history' permission was needed, or what functionality it related to.

**Describe the solution you'd like**

In order for users to better understand before or after installing ThirdStats, the rationale for required permissions, and remove any barriers or hesitation with respect to the privacy/security of their data ...

 - [x] Review present ThirdStats Thunderbird Permissions requirements (see screenshot)
 - [x] Remove permissions that are not required to provide ThirdStats functionality (where possible to do so)
  * Why does thirdstats need acess to (all?) browser tabs? Is this *required*, or linked to a specific thirdstats feature? Can these be scoped to only ThirdStats tabs?
 - [x] Replace currently *unconditional* permissions with conditional/options permissions, where possible.
 - [x] Split permissions for wider scoped permissions to more granular / separate permissions (where possible)
  * For example, if thirdstats doesn't use email content/bodies (at the moment or at all), is there a permission just to access email metadata? If not, could we ask for them?
 
 - [x] Document ThirdStats permission requirements, linking them with plain language descriptions of the ThirdStats feature that required them, in ...
   - [x] The ThirdStats repository README.txt
   - [x] The ThirdStats Mozilla Addons Description
   - [ ] The ThirdStats "options" page (in the "Notes" section)
     - [x] Make "Note" a proper/full-size section header

Edit: I note permissions are documented in the repo: https://github.com/devmount/third-stats/blob/master/SECURITY.md#3-what-exactly-are-all-the-permissions-used-for

**Describe alternatives you've considered**

None

**Additional context**

![2021-02-25 10_44_17-Add-ons Manager - Thunderbird Daily](https://user-images.githubusercontent.com/1011612/109082242-795dee80-76fb-11eb-9428-3b88f1f04995.png)

**Comment by devmount** [comment]
Thank you so much, @koobs for this detailed well-written security and documentation enhancement request 👏🏻

> only use permissions that are _necessary_ to provide the functionality desired by the user, and where possible, use _optional_ permissions that can be enabled on a per-feature level.

This is what ThirdStats always aimed to do. Unfortunately, the permissions API of Thunderbird is poor, there are no fine-grained permissions or mechanisms to activate permissions per-feature 😞

> Why does thirdstats need acess to (all?) browser tabs? Is this _required_, or linked to a specific thirdstats feature? Can these be scoped to only ThirdStats tabs?

This was such a valuable hint, the `tabs` permission was actually not needed to open tabs (which I first thought given the docs). I tested it now without this permission and it still works - so one permission less 👏🏻

> For example, if thirdstats doesn't use email content/bodies (at the moment or at all), is there a permission just to access email metadata? If not, could we ask for them?

ThirdStats doesn't use email bodies at all, but as I already said: Unfortunately there is no permission for only email-headers. Maybe you can create a permission request in the TB repo for that?

> The ThirdStats "options" page (in the "Notes" section) 

I added the permissions description on all your proposed places, except this one. Since this is now in the general add-on description, it is duplicated and a little out of place on the options page (IMHO).

**Comment by koobs** [comment]
> This is what ThirdStats always aimed to do. Unfortunately, the permissions API of Thunderbird is poor, there are no fine-grained permissions or mechanisms to activate permissions per-feature 😞

I'd explicitly document this, so to users its clear we're always trying to minimise scope where possible. Something like "ThirdStats will always seek to minimise use of permissions where possible, and use granular permissions where available. Thunderbirds Permissions API is currently limited ..."

> This was such a valuable hint, the `tabs` permission was actually not needed to open tabs (which I first thought given the docs). I tested it now without this permission and it still works - so one permission less 👏🏻

🥳 


> ThirdStats doesn't use email bodies at all, but as I already said: Unfortunately there is no permission for only email-headers. Maybe you can create a permission request in the TB repo for that?

I dont have Mozilla/etc accounts for submitting these at present, but may consider it if I happen to end up doing, or planning to do a lot of this. Do they have places @ GitHub to do this? (If i recall correctly, TB uses BMO unlike some Firefox projects) If so, can do.



> I added the permissions description on all your proposed places, except this one. Since this is now in the general add-on description, it is duplicated and a little out of place on the options page (IMHO).

I'm a fan of 'cant be *too* transparent' with respect to privacy / security and messaging for users, but your call :) Thanks for taking care of that in the addons description <3

**Comment by devmount** [comment]
> I'd explicitly document this, so to users its clear we're always trying to minimise scope where possible.

Great point! I added this 👍🏻 (also, since I'm no English native, it's such a great help that you even provide a possible formulation 😍)

> If i recall correctly, TB uses BMO

Afaik yes - though I'm not sure if this is also for feature requests. Thank you for anything that triggers an improvement to the permissions API! 👏🏻

> Thanks for taking care of that in the addons description <3

My pleasure 😊

**Comment by devmount** [comment]
Just for reference: Unfortunately my efforts for a finer grained permission policy for reading message headers won't be implemented in Thunderbird:
https://bugzilla.mozilla.org/show_bug.cgi?id=1779640#c9
