### ISSUE TITLE
Improve several options default values [UX]

### ISSUE THREAD

**Issue by koobs** [devmount/third-stats#272]
**Is your feature request related to a problem? Please describe.**

Users have diverse and unique preferences, and it is impossible for software authors to prescribe a single set of software configuration values that will satisfy everyone. Accordingly, it is important for software *default* values to be set according to other, not subject to subjective variability, principles.

At present, there are a number of settings who's default values I believe can be improved:

 * Appearance & Experience -> Dark Mode (Default: Enabled)
 * Appearance & Experience -> Vertical Axis (Default: Disabled)
 * Charts & Data -> Start the Week on  (Default: Sunday)
 * Charts & Data -> Active Accounts [ ] Local Folders (Default: Disabled)

**Describe the solution you'd like**

 * Appearance & Experience -> **Dark Mode (Default: Disabled)**
   * Perhaps the author has preferences for dark mode. Author preferences should ideally not be brought to bear on defaults when distributing to users.
   * **Rationale**: Out of the box, system and application themes are not dark by default. Further, Dark by default in most default cases, has ThirdStats appear inconsistent with the Thunderbird theme, *UNLESS* ...
   * A `System Settings/Theme` option can be added that follows the current system theme. To be the default.
 * Appearance & Experience -> **Vertical Axis (Default: Enabled)**
   *  **Rationale**: New users onboarding/understanding is impacted by the lack of labels, which impedes learning quickly.
   * Also "Always label your axis" is a common comment with regard to graphing, as it provides immediate and specific context as to what data dimensions are being graphed. Removing said axis labels is a great option, for users to choose _once they are familiar_ 
 * Charts & Data -> Start the Week on  (Default: Sunday)
   * **Proposed**: If possible and available, ThirdStats should use the current locale/regional settings, which provides this (first day of week) value, or failing that the local of the current thunderbird installation.
 * Charts & Data -> Active Accounts [ ] Local Folders (Default: Disabled)
   * **Proposed**: All accounts 'active' (enabled) by default.
   * **Rationale**: ThirdStats cannot predict the mail layout, hierarchy or organizational scheme of its users. The default (Local Folders: Disabled) assumes local folders are not useful or relevent (perhaps the author does not use local folders, like me).

**Comment by devmount** [comment]
Thank you for this detailed description again 👏🏻 

> Appearance & Experience -> **Dark Mode (Default: Disabled)**

Agreed. When implementing the theming I checked the possibility to get the theme scheme, but unfortunately [it was not possible](https://thunderbird.topicbox.com/groups/addons/Tcbce37425677928e-Mfef95e3f5102cdfafb5c3110).

> Appearance & Experience -> **Vertical Axis (Default: Enabled)**

Agreed.

> Charts & Data -> Start the Week on  (Default: Sunday)

Agreed. I'll see if I can retrieve the first weekday preference from a locale.

> Charts & Data -> Active Accounts [ ] Local Folders (Default: Disabled)

I assumed the default configuration for the majority of users is one non-local account and the default local account created by TB. But I guess it wouldn't hurt if all accounts are active by default. So agreed again 👍🏻
