### ISSUE TITLE
Total email storage space and filter for email storage sizes

### ISSUE THREAD

**Issue by squalof** [devmount/third-stats#277]
Ciao,

prima di tutto complimenti per aver sviluppato queta estensione "thirdstats"perchè è davvero molto utile.

Ti chiedo gentilmente, se puoi con un aggiornamento inserire la possibilità di visualizzare il peso totale delle email sia ricevute che inviate inserendo anche la possibilità di impostare il limite massimo di archiviazione delle email del proprio account di posta elettronica, grazie.

In attesa, saluti.

Antonio

**Comment by koobs** [comment]
Translation:

```
Hi,

first of all congratulations for developing this "thirdstats" extension
because it is very useful.

I kindly ask you, if you can, with an update, insert the possibility to
view the total weight of the emails both received and sent, by also
inserting the possibility of setting the maximum storage limit of
the emails of your email account, thank you.

Antonio
```

**Comment by devmount** [comment]
`EN`

@koobs Thank you for the translation service. 👏🏻 

@squalof Thank you for these feature ideas! 👍🏻 

> insert the possibility to view the total weight of the emails both received and sent

What do you mean exactly? The sum of the storage size of each email? Unfortunately it's currently not possible to retrieve this kind of information via WebExtension APIs. See #213

> setting the maximum storage limit of the emails of your email account

Do you mean an additional filter for storage sizes? As soon as #213 is possible, such a filter can be implemented.

---

`IT`

@koobs Grazie per il servizio di traduzione. 👏🏻 

@squalof Grazie per queste idee di funzionalità! 👍🏻 

> inserire la possibilità di visualizzare il peso totale delle email sia ricevute che inviate inserendo

Cosa intendi esattamente? La somma delle dimensioni di archiviazione di ogni email? Purtroppo al momento non è possibile recuperare questo tipo di informazioni tramite le API di WebExtension. Vedi #213

> la possibilità di impostare il limite massimo di archiviazione delle email del proprio account di posta elettronica

Intendi un filtro aggiuntivo per le dimensioni di archiviazione? Non appena #213 sarà possibile, tale filtro potrà essere implementato.

Tradotto con www.DeepL.com/Translator (versione gratuita)

**Comment by devmount** [comment]
`EN`

@squalof If you'd like to answer the questions above and give more details for your feature request, feel free to reopen this issue.

---

`IT`

@squalof Se vuoi rispondere alle domande di cui sopra e dare più dettagli per la tua richiesta di funzionalità, sentiti libero di riaprire questo problema.
