### ISSUE TITLE
Emails >KW47 2020 not detected

### ISSUE THREAD

**Issue by behinger** [devmount/third-stats#289]
**Describe the bug**
Maybe I missed a setting somewhere?! But emails later than KW47 2020 are somehow not included (even though plenty exist ;-)). 
The bug likely occurs already in KW46 because there are much fewer emails there, as are expected.

**To Reproduce**
Simply select any of my email accounts, press the "refresh". This doesnt show anything for three accounts with ~2000 & 5000 50.000 emails detected. 

**Expected behavior**
All my emails should be visible

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10183650/112733535-d76f3300-8f40-11eb-9e5b-52498a17f6c2.png)

**System (please complete the following information):**
- OS: Win10
- Thunderbird Version 78.9

Unfortunately I dont really know how to even start debugging this :-)

PS: Cool looking addon, very nice :-)

**Comment by devmount** [comment]
Hi Benedikt,
thanks for reporting this, it's indeed strange. It seems like ThirdStats stops processing emails on a specific date. Are there any error messages in the console (main menu > add-ons > gear > debug add-ons > scroll to ThirdStats > Inspect)?

Can you run the following snippet in the console and see, if there are any error messages? This counts all messages of all folders of all accounts:

```javascript
let accounts = await messenger.accounts.list(); let allfolders = []; let count = 0;
accounts.map(a => { function traverse(folders) { if (!folders) return; for (let f of folders) { allfolders.push(f); traverse(f.subFolders); }} traverse(a.folders);})
await Promise.all(allfolders.map(async f => { let page = await messenger.messages.list(f); page.messages.map(m => count++); while (page.id) { page = await messenger.messages.continueList(page.id); page.messages.map(m => count++); } })).then(() => { console.log(count); });
```

> PS: Cool looking addon, very nice :-)

Many thanks 😊

**Comment by behinger** [comment]
Thanks!

This piece of code returns:
> 93801 debugger eval code:30:13
> undefined

I am guessing this is 93800 emails. But the dashboard stillshows only 54600

**Comment by devmount** [comment]
Thank you. Can you share an actual screenshot?

**Comment by behinger** [comment]
![grafik](https://user-images.githubusercontent.com/10183650/112839311-55951c00-909e-11eb-8b17-0f3207d7d5e0.png)

**Comment by devmount** [comment]
> I am guessing this is 93800 emails. But the dashboard stillshows only 54600

It's 93801 emails as the sum of all your TB accounts. Good thing is, the message retrieval seems to work on your end. This may be trivial, but did you filter anything (folder, date range, contacts)? What happens, if you select "All accounts" (Alle Konten)?

![image](https://user-images.githubusercontent.com/5441654/112844007-89267500-90a3-11eb-8328-cf88877fd58c.png)

> (at startup I get some errors in L10nRegistry.jsm, ActivityManager.js, panel.js and when resizing - any of those of interest?)

No, they are TB 78 related.

**Comment by devmount** [comment]
@behinger Any news on this? Did you try the account filter? Let me know if you need any further help, otherwise I'll close this.

**Comment by behinger** [comment]
Sorry for not responding. I wanted to do more tests. But after removing all restriction of accounts (via settings) and then putting them back into place, it works now.

Not sure what's going on. Can be closed

Am 25. April 2021 20:32:27 MESZ schrieb Andreas ***@***.***>:
***@***.*** Any news on this? Did you try the account filter? Let me know

**Comment by devmount** [comment]
I see, glad it works now 👍🏻
