### ISSUE TITLE
hu translations of strings beginning with a number all in lowercase

### ISSUE THREAD

**Issue by ovari** [devmount/third-stats#295]
Can the hu translations of strings beginning with a number please be all in lowercase, i.e. `{0} fiók`, `{0} mappa` and `{0} üzenet`?

![image](https://user-images.githubusercontent.com/17465872/113055774-b6376c80-91f6-11eb-8289-e176e1828906.png)

The translations seem to be from: https://github.com/devmount/third-stats/blob/master/public/_locales/hu/messages.json#L78-L82

However, `Fiók` and `Mappa` should start with a capital letter as shown in the image below.

![image](https://user-images.githubusercontent.com/17465872/113056512-9ce2f000-91f7-11eb-8bc7-5999baba166c.png)

Thank you

**Comment by devmount** [comment]
Thank you for reporting this. I totally agree, I'll improve the lang files to use separate keys for the locations you mentioned.

**Comment by ovari** [comment]
You might also like to use [Localization and Plurals](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals).

There is no difference in Hungarian when there is a number before the object; however in English it is:
* `1 account`, `2 accounts`
* `1 folder`, `2 folders`
* `1 message`, `2 messages`

Other languages have different plural forms so you add-on can also benefit from using the 19 different plural forms.

Thank you

**Comment by ovari** [comment]
Can you please program it just like [Localization and Plurals](https://developer.mozilla.org/en-US/docs/Mozilla/Localization/Localization_and_Plurals)? The Hungarian rules are just like that. Sorry, creating a pull request to do that is out of our scope as we only translating in the browser, there is no copy on our computer of your add-on.

Plural rule #1 (2 forms) is the form used by English and Hungarian, so when English is done, it can be used for Hungarian.

Thank you once again.

**Comment by devmount** [comment]
I see, so there is no need for an additional pluralizationRules object for Hungarian, since it works with the English one. Once I corrected the keys, you can provide the correct plural form. I let you know, when it's done.

**Comment by devmount** [comment]
It's implemented now. I already corrected the Hungarian translation to lowercase.
