### ISSUE TITLE
Slow/endless analyzing of mails

### ISSUE THREAD

**Issue by konrad79** [devmount/third-stats#298]
The performance of the stat extension seems to be endless slow.
Is there any type of progress view? The extension runs for hours now on the account "Local Folders" with about 50.000 mails in it.
And is this process only performed once over the full data and after that only the new / added mails are analyzed?

**Comment by devmount** [comment]
Hi there,

with 50k mails processing should be completed in 30s. Seems like you are one of those affected by #19 - please try the steps described in https://github.com/devmount/third-stats/issues/19#issuecomment-732659173 and the follow up posts. If you get the same error messages ("folder not found") you'll have to wait for the next Thunderbird major release, I'm afraid.
Also make sure, that your folder names don't contain any special characters (like `@` or `+`), as Thunderbird is currently unable to handle them - see #223.

**Comment by konrad79** [comment]
Thanks @devmount  - there are 1130 folders listed in the debug console - this seems to be ok.
Are there other forbidden special characters than @ and + ? What about Umlauts like "ä" or "ü" or something like "_"

**Comment by devmount** [comment]
> there are 1130 folders listed in the debug console - this seems to be ok.

What about the follow up check for the overall emails count described in https://github.com/devmount/third-stats/issues/19#issuecomment-732847917?

```javascript
let accounts = await messenger.accounts.list(); let allfolders = []; let count = 0;
accounts.map(a => { function traverse(folders) { if (!folders) return; for (let f of folders) { allfolders.push(f); traverse(f.subFolders); }} traverse(a.folders);})
await Promise.all(allfolders.map(async f => { let page = await messenger.messages.list(f); page.messages.map(m => count++); while (page.id) { page = await messenger.messages.continueList(page.id); page.messages.map(m => count++); } })).then(() => { console.log(count); });
```

> Are there other forbidden special characters than @ and + ? What about Umlauts like "ä" or "ü" or something like "_"

Not that I know of, umlauts and underscore are working fine on my end.

**Comment by konrad79** [comment]
The last command throws 3 times the same Error:
`"Component returned failure code: 0x80550005 [nsIMsgFolder.messages]"  nsresult: "0x80550005 (<unknown>)"  location: "JS frame :: chrome://messenger/content/parent/ext-messages.js :: list :: line 193"  data: no]
"Component returned failure code: 0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST) [nsIMsgFolder.messages]"  nsresult: "0x80520006 (NS_ERROR_FILE_TARGET_DOES_NOT_EXIST)"  location: "JS frame :: chrome://messenger/content/parent/ext-messages.js :: list :: line 193"  data: no]`

**Comment by devmount** [comment]
Interesting. Which Thunderbird Version? Which OS?

**Comment by konrad79** [comment]
Thunderbird: 78.9.1 (32bit)
Windows: 10 Build 19041

**Comment by devmount** [comment]
Ok, the error happens outside of the scope of this add-on, so I'm afraid I cannot fix it on my end. You can either create a bug report on [bugzilla](https://bugzilla.mozilla.org) or wait for the next major release of Thunderbird and give ThirdStats a second try then (which will be on 2021-07-27 according to the [release calendar](https://wiki.mozilla.org/Release_Management/Calendar)).
