### ISSUE TITLE
Add translation: French

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#3]
**Provide the name and the two-letter code of the new language**
French, `fr`

**Steps to add the translation**
- Add a folder `public/_locales/fr/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

**Comment by feyre-2001** [comment]
Would love to work on this issue!

**Comment by feyre-2001** [comment]
Thanks for assigning! Would get it done in a week or less :)

**Comment by devmount** [comment]
Thanks for contributing! And no rush - take your time 😎
