### ISSUE TITLE
Data collection stuck at 91.3%

### ISSUE THREAD

**Issue by kswartz26** [devmount/third-stats#302]
I am using version 1.6.0 of the addon in Thunderbird 78.10.0, with an account that has somewhere in the vicinity of 200,000 messages. I have yet to see the reports - every time I try to start it up, the data collection gets stuck at 91.3% complete, with the CPU still running high.

Below is the output from the debug console. Everything you see here is displayed within the first few seconds. ("Inbox > Non-3PLTA Today" is a saved search folder. That message comes up right away, not when the collection hangs. There are five other saved search folders, though, and it doesn't complain about any of those.) When it hits 91.3% after about 90-120 seconds, there are no additional messages indicating what is causing the hang.

Let me know what other information I can try to collect for you. Thanks!

![image](https://user-images.githubusercontent.com/18671894/116015010-a9871800-a5ec-11eb-8cba-50a42ef48051.png)

**Comment by devmount** [comment]
Hi Keith,

thanks for reporting this. Unfortunately, special characters in search folder names make a lot of trouble in Thunderbird and as extension developer, I don't have any possibility to fix this (yet, I reported it some time ago https://bugzilla.mozilla.org/show_bug.cgi?id=1688612).

Can you check, if this issue is caused by the space character in your search folder name? E.g. does it work, if you rename it to `Non-3PLTA-Today`? This may be a possible workaround.

**Comment by kswartz26** [comment]
That was it. I only had to remove the spaces in the saved search folders; it didn't pose a problem in the normal folders. Just for good measure, I also found two folders with an & and a ' in them, and removed those.

This might be a good thing to add to the docs, since, as you said, there's a pretty easy workaround. Thanks for the quick response!

**Comment by devmount** [comment]
Glad it works, and thanks for reporting those additional characters. I will recheck this as soon as the next major release of Thunderbird landed this summer, as there will be a lot of core changes.

> This might be a good thing to add to the docs

Very good idea, a "known issues" section or page somewhere in ThirdStats would be helpful for users. I try to figure out how this can be automated somehow.

> Thanks for the quick response!

You're very welcome.

**Comment by devmount** [comment]
FYI the above mentioned bug report got fixed in TB 90 and will be part of TB 91 in summer.
