### ISSUE TITLE
Thirdstat is blocked when indexing the mails

### ISSUE THREAD

**Issue by fruitconfit** [devmount/third-stats#311]
When I launch the thirstat indexing, is starts then is blocked (for hours) at something like 70%. This may be a special case with my mail box... 
![image](https://user-images.githubusercontent.com/58135163/117310020-41092800-ae83-11eb-82c8-a6c3f23da6e5.png)

- OS: Windows 10
- Thunderbird Version 78.10.1

With the same thunderbird installation, but on a different profile, the same thirdstat plugin (of course) works perfectly.

**Comment by devmount** [comment]
Hi there,
looks like that profile/account is affected by #19 - please try the steps described in https://github.com/devmount/third-stats/issues/19#issuecomment-732659173 and the follow up posts. If you get the same error messages ("folder not found") you'll have to wait for the next Thunderbird major release, I'm afraid.
Also make sure, that your folder names don't contain any special characters (like `@` or `+`), as Thunderbird is currently unable to handle them - see #223.

**Comment by fruitconfit** [comment]
Thanks for the quick reply!

At least on folder can not be parsed (using the code snippets provided 
in #19). There '#' caracters in this folder, but I have a lot like 
this... so never mind, I won't use thirdstat on this account.

Best regards


Le 06/05/2021 à 16:36, Andreas a écrit :

**Comment by devmount** [comment]
You're welcome. Afaik the problem with special chars in folder names has already been fixed and will be part of the next major release of Thunderbird. Nevertheless thanks for reporting.
