### ISSUE TITLE
Not compatible with Thunderbird 91.0.1

### ISSUE THREAD

**Issue by Dtrieb** [devmount/third-stats#347]
- OS: Windows 10
- Thunderbird Version 91.0.1 (64-Bit)

Addon seems not compatible 

![thunderbird_2021-08-18_14-15-35](https://user-images.githubusercontent.com/3650284/129896413-56c9804a-50d1-42dc-a947-c7a022b389ec.png)
![thunderbird_2021-08-18_14-15-00](https://user-images.githubusercontent.com/3650284/129896432-8e1d5f23-f8d3-4b5e-9faf-ec80da68bba6.png)

**Comment by devmount** [comment]
Thank you for reporting this - I'm using ThirdStats in TB 91.0.1 on Win 10 without problems, I'll have a look at this.

**Comment by Dtrieb** [comment]
But I install it with drag and drop without any problem.

**Comment by devmount** [comment]
Ok, this seems to be a bug on AMO. I'll report this to the Thunderbird devs and let you know, when there's a solution.

**Comment by jobisoft** [comment]
@Dtrieb : Can you describe how you got that screenshot? If I search for thunder stats in the add-on manager, the result list looks totally different. (and does not show an error)

**Comment by Dtrieb** [comment]
![thunderbird_2021-08-18_15-18-52](https://user-images.githubusercontent.com/3650284/129905195-61e89e9c-3663-4dfe-9fa0-624821f8cdb2.png)

I search in Thunderbird on this for: ThirdStats
It opened in Thunderbird in a new Tap: https://addons.thunderbird.net/de/thunderbird/search/?q=ThirdStats

There I get this:

![thunderbird_2021-08-18_15-22-41](https://user-images.githubusercontent.com/3650284/129905707-5b48fd43-5eab-41f2-94bf-b0bb7cb58420.png)

**Comment by jobisoft** [comment]
Is this limited to ThirdStats? What do you get for TbSync or Quicktext?

**Comment by Dtrieb** [comment]
TbSync = Didn't compatible
Quicktext = Compatible

**Comment by jobisoft** [comment]
Hm, can you close and restart TB and recheck Quicktext? Still compatible? And after that, could you try with a new profile (all 3 add-ons)?

**Comment by Dtrieb** [comment]
After close and restart TB Quicktext still compatible!

With a new Profil all 3 Addons work!

**Comment by jobisoft** [comment]
I have no idea what is up with your original profile. Could you go through the preferences and look for any non-standard value which could be related?

**Comment by Dtrieb** [comment]
Okay. Thank you for your support.

I install it with drag'N'drop that work for me.
You can close this if you want.

**Comment by devmount** [comment]
@jobisoft Thank you John for taking the time to look into this!

@Dtrieb Glad it works for you at least this way. I'll close this, but if you have any new information on this you can still comment here for any possible future users with the same problem.
