### ISSUE TITLE
Heatmap distribution colors are not visible

### ISSUE THREAD

**Issue by zach-hartwig** [devmount/third-stats#359]
**Describe the bug**
The heatmap visualization of "Activity" and "Temperal Distribution" does not appear to be working. All of the other charts appear graphically correct. When I hover over each cell in the heatmap, I get data in the pop up from the mouse that appears correctly. Thus, this problem seems to be a graphical issue involving the coloring or display of the cells?

**To Reproduce**
Other than installation on my particular system, simply view the ThirdStats tab.

**Expected behavior**
I would expect the colored heatmaps to appear as they are shown in the example visualization.

**Screenshots**
![image](https://user-images.githubusercontent.com/4530230/138582420-2850b5e4-d4f5-4ec7-b516-85927f6511aa.png)

**System (please complete the following information):**

- OS: Fedora 33 XFCE (kernel 5.10.7-200)
- Thunderbird Version: 91.1.0

Thanks very much for writing this awesome add-on. It's incredibly easy to use and visualization is terrific.

**Comment by devmount** [comment]
In #367 the heatmaps got reimplemented as matrix charts, which now will no longer depend on the custom color settings of Thunderbird. This will be part of the next release and you can continue using your Thunderbird color settings with ThirdStats.
