### ISSUE TITLE
erreur thirdstats

### ISSUE THREAD

**Issue by pads54fr** [devmount/third-stats#362]
**Describe the bug**
Disparition de la couleur bleue dans certains graphiques (activités). Pourtant, lorsque l'on survole la zone, on obtient bien le nombre de messages par unité.

**To Reproduce**
Click sur le bouton "thirdstats "
Pas de message d'erreur

**Expected behavior**
Graphique avec les couleurs

**Screenshots**
![image](https://user-images.githubusercontent.com/97067672/148680306-ae770d5b-879d-4757-8f04-7065a3a0e539.png)

**System (please complete the following information):**

- OS:Windows 11
- Thunderbird Version 91.4.1 (64 bits)

**Additional context**
nihil
![th anomalie thirdstats 1](https://user-images.githubusercontent.com/97067672/148680353-caabec59-33d6-4abf-9213-99fa013e6b15.png)
![th anomalie thirdstats 2](https://user-images.githubusercontent.com/97067672/148680364-a212b623-f20c-4652-b971-1e883b840c95.png)
![th anomalie thirdstats 3](https://user-images.githubusercontent.com/97067672/148680368-4959fef8-ee2a-4b6a-b01e-1d4040358d5f.png)

**Comment by devmount** [comment]
Thank you @pads54fr for reporting this. This is most likely the same problem as in #359. ThirdStats is currently not able to show the correct colors if a high contrast theme is activated in Thunderbird as described in https://github.com/devmount/third-stats/issues/359#issuecomment-952864292.

I'm afraid you'll have to activate normal colors again, until I solved this by reimplementing the heatmaps.
Bonne semaine à toi !

**Comment by devmount** [comment]
In #367 the heatmaps got reimplemented as matrix charts, which now will no longer depend on the custom color settings of Thunderbird. This will be part of the next release.
