### ISSUE TITLE
Please add a ThirdStats icon to the Thunderbird Spaces Toolbar

### ISSUE THREAD

**Issue by ovari** [devmount/third-stats#382]
Thunderbird version 102 has a Spaces Toolbar.
https://blog.thunderbird.net/2022/09/thunderbird-tip-customize-colors-in-the-spaces-toolbar/

Can a ThirdStats icon please be added to the Thunderbird Spaces Toolbar?

Perhaps code pointers from the CardBook add-on can help as a CardBook icon shows in the Spaces Toolbar.
https://addons.thunderbird.net/thunderbird/addon/cardbook/
https://gitlab.com/CardBook/CardBook/

What do you think?

Thank you

**Comment by devmount** [comment]
Thanks @ovari that is a great idea! I checked the webextension API and found that there already is an API for that:
https://webextension-api.thunderbird.net/en/102/spacesToolbar.html#functions

Will definitely implement this 👌🏻

**Comment by devmount** [comment]
This is implemented now and part of the next release.

**Comment by ovari** [comment]
Thank you
