### ISSUE TITLE
Outgoing mails are sometimes counted twice

### ISSUE THREAD

**Issue by SolidTux** [devmount/third-stats#389]
**Describe the bug**

My outgoing mail count is too large (e.g. 21 for today even though I only sent 12). It seems like most mails are counted twice. This might be because I most of the time send a copy to myself or write to a list that I'm also subscribed to. Maybe especially the second part could be hard to match as the mailling list rewrites the subject, so it's not exactly the same mail.

For me it would be fine to have an option to ignore the "sent" folders and only count mails from my own account in all other folders.

**To Reproduce**

* Have outgoing mails in multiple folders
* Look at account statistics

**Expected behavior**

The number of outgoing mail matches the one shown in the stats.

**Screenshots**

stats:

![Screenshot_20221123_150739](https://user-images.githubusercontent.com/17935831/203568551-ad65de4f-246d-4598-b612-8306ab810ee6.png)

outgoing mails:
![Screenshot_20221123_150819](https://user-images.githubusercontent.com/17935831/203568653-cde0c789-dc32-4550-bce0-08ba9d5a75b2.png)

There is one additional mail not shown here in a different folder (because another device that I use puts them in a different folder).

**System (please complete the following information):**

- OS: Debian 
- Thunderbird Version 102.5.0

**Additional context**

**Comment by devmount** [comment]
Hi Daniel,

thank you for this report. Some questions first:

>  I most of the time send a copy to myself

Do you just mean the emails in your _Sent_ folder here? Or do you CC one of your email addresses and have a sent email as well as an additional copy?

> or write to a list that I'm also subscribed to

Normally this shouldn't be a problem, as long as you didn't configure the mailing lists email address as an own identity. ThirdStats can't and won't check emails if they are the same.

Things you can do:

1. ThirdStats recognizes all emails as _sent_, when their sender is an email address from any identity set in your Thunderbird Accounts. Please check if you configured that correctly (You can do so under _account settings_ > select your account > click button _more identities_ at the bottom).
2. In the ThirdStats add-on options there is a setting to ignore self-sent emails. If you enable this, ThirdStats ignores emails where both, the sender and receiver, are email addresses you configured as own identities.

![image](https://user-images.githubusercontent.com/5441654/203748072-8da48fac-8668-457f-826d-abe041626e4e.png)

Let me know, if this was helpful. I consider providing an add-on option, where you can define folders you don't want to include in the stats processing.

**Comment by SolidTux** [comment]
> thank you for this report

Thank you for the fast response!

> Do you just mean the emails in your Sent folder here? Or do you CC one of your email addresses and have a sent email as well as an additional copy?

I **B**CC all the mails to the same address. E.g. if I'm writing from `mail@example.com` there is a rule on the server to automatically add a BCC to `mail@example.com`. And exactly that happens then, 1 mail in the inbox and 1 in the "sent" folder.

One option of course would be to delete everything in the "sent" folder as I don't need that anyways. But an option to ignore certain folders would be awesome (this would also be handy on my other account, where I don't care about mails in some folders), but I of course have no idea how time consuming this would be to implement.

    or write to a list that I'm also subscribed to

> ThirdStats recognizes all emails as sent, when their sender is an email address from any identity set in your Thunderbird Accounts. Please check if you configured that correctly (You can do so under account settings > select your account > click button more identities at the bottom).

That it set correctly.

> In the ThirdStats add-on options there is a setting to ignore self-sent emails. If you enable this, ThirdStats ignores emails where both, the sender and receiver, are email addresses you configured as own identities.

Does this also recognize BCC and not only CC?

**Comment by devmount** [comment]
I see.

> Does this also recognize BCC and not only CC?

Yes it should, but you can simply test it for your scenario. You can choose between matching identities from the same account or all your Thunderbird accounts. Keep in mind that after changing that setting in the add-on options, you once need to reprocess the stats data to rebuild the cache.

**Comment by devmount** [comment]
@SolidTux Any news on this?

**Comment by SolidTux** [comment]
Sorry, I ended up not really needing/using the extension anymore.
