### ISSUE TITLE
Option to sync ThirdStats theme with Thunderbird theme

### ISSUE THREAD

**Issue by DenB10** [devmount/third-stats#396]
Hi Andreas,

First of all, congratulations again (already done on ATN) for your wonderful add-on.

I would like to present you a request that I think could be an improvement: synchronize the theme of ThirdStats with the theme of Thunderbird that the user has chosen and not by a manual setting on the options page.
To tell you the truth, I'm using another add-on called  [Dark Reader](https://addons.thunderbird.net/thunderbird/addon/darkreader/) that I've configured to change the theme depending on the time of day and I'd like the ThirdStats theme to match it.

Best regards

**Comment by devmount** [comment]
Hi @DenB10,

thank you for your support on ATN and this feature request. Making the ThirdStats theme depend on the Thunderbird Theme is a great idea, will try to implement an _auto_ option for the theme selection. I cannot guarantee that it will work with third party add-ons like Dark Reader though.

**Comment by devmount** [comment]
Hi @DenB10, this is implemented now. If you like, you can [try the latest ThirdStats build](https://third-stats.cdn.devmount.com/). I tested with the Thunderbird default themes.

**Comment by DenB10** [comment]
Tested and approved. Good work, thank you very much.

**Comment by devmount** [comment]
Great, will be part of the next release (which will hopefully come in the next couple of weeks). Thanks for the quick test!
