### ISSUE TITLE
Add translation: Chinese

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#4]
**Provide the name and the two-letter code of the new language**
Chinese, `zh`

**Steps to add the translation**
- Add a folder `public/_locales/zh/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

**Comment by Manoj13-coder** [comment]
i like to contribute assign it to me

**Comment by devmount** [comment]
Hi @Manoj13-coder,
at first: Thank you for your interest and that you'd like to contribute to this project. I've seen you also applied to Russian, Portuguese and Italian. Can you somehow prove that you fluently speak all these languages? No offense, but I'd rather assign native speakers here. Thanks for your understanding.

**Comment by Manoj13-coder** [comment]
assign it to me i will do it

**Comment by Hsins** [comment]
@devmount Would you mind to assign it to me? Moreover, there are Traditional Chinese and Simplified Chinese in the world. I think that it's a better idea to divide this issue into two different issues:

- Traditional Chinese, `zh-tw`
- Simplified Chinese, `zh-cn`

I would help to translate the Traditional Chinese part.

**Comment by devmount** [comment]
Thank you very much, Sean, for this great suggestion and your help! I splitted this issue accordingly into #66 and #67. Please add a comment on the former one, so that I can assign it to you.
Thanks again!
