### ISSUE TITLE
Processing for account with 150k emails is stuck

### ISSUE THREAD

**Issue by hurvajs** [devmount/third-stats#403]
**Describe the bug**
When I want to show statistic for a small email account (100-10000 emails) it works.
But when I need statistic for our standard email account (cca 150000 emails, 30 GB) is stuck forever while loading...

**To Reproduce**

![obrazek](https://user-images.githubusercontent.com/14957815/227955239-4f8bb40c-b9df-4ba9-aca5-1050c8faebd4.png)

**Expected behavior**
the data should load

**System (please complete the following information):**

- OS: Windows 10
- Thunderbird Version 102.6.1 (64-Bit)

**Comment by devmount** [comment]
I released version 1.10.0 with a possible bug fix for your problem. Please report again, if you still have troubles processing that large account.
