### ISSUE TITLE
Translations - plural forms

### ISSUE THREAD

**Issue by wikiyu** [devmount/third-stats#41]
**Is your feature request related to a problem? Please describe.**

There is a lot of languages with more than two forms - singular and plural. For example in polish (and most of slavic languages) we have 
1 comment - 1 komentarz
2 comments - 2 komentarze
5 comments - 5 komentarzy
here we have two different forms of plurals. But ... there is much more fun in this area. 
https://doc.qt.io/archives/qq/qq19-plurals.html - in QT library docs is quite nice example 

**Describe the solution you'd like**

Best method that i even know about translations with support of many plural (and null) forms is gettext https://www.gnu.org/software/gettext/
with poEditor - tool to make very fast translations, and even online tool. As i found there is also javascript gettext implementation.
https://github.com/guillaumepotier/gettext.js/

**Describe alternatives you've considered**

**Additional context**

https://www.gnu.org/software/gettext/manual/gettext.html#Translating-plural-forms

**Comment by devmount** [comment]
Thank you for this request. This add-ons internationalization is built on [vue-i18n](https://github.com/kazupon/vue-i18n), which has an option for custom pluralization:
https://kazupon.github.io/vue-i18n/guide/pluralization.html#custom-pluralization

So you just have to pass an optional `pluralizationRules` object into VueI18n constructor options.
@wikiyu Can you formulate these rules for Polish and create such an object?

**Comment by devmount** [comment]
Are you still interested in this feature request? If yes, I need some help creating the corresponding object to implement the special pluralization. @wikiyu @dfoltynski ?

**Comment by devmount** [comment]
@wikiyu Thanks to @arndissler, we now have Polish pluralization rules implemented. You can now translate [l.6 of `pl/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/pl/messages.json#L6) like this: `"Konto | Konta | Kont"`

Would be awesome if you find some time to translate Polish to the latest state. You can use our [localization tool](https://gitlocalize.com/repo/5505) for this (see #135). Wielkie dzięki!
