### ISSUE TITLE
global counters not centered on the ultrawide screen

### ISSUE THREAD

**Issue by kerlon5** [devmount/third-stats#46]
![image](https://user-images.githubusercontent.com/26476861/95227424-8b57f700-0817-11eb-80a6-562e6fcedd78.png)

- Windows 7
- Thunderbird Version 78.3.1 (64-bit)
- 2560x1080 resolution

**Comment by devmount** [comment]
Thank you for reporting this! I fixed it. The fix will be part of the next release.
