### ISSUE TITLE
Complete translation: Catalan

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#49]
**Provide the two-letter code of the existing language**
`ca`

**Provide the lines, that are still English and should be translated**
24-25, 56-57, 60-61

**Steps to complete the translation**
- Open the corresponding file, `public/_locales/ca/messages.json`
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by Leos1113** [comment]
Can you assign me this issue?

**Comment by devmount** [comment]
Sure, thank you for your help!

**Comment by Leos1113** [comment]
https://github.com/devmount/third-stats/pull/87 done!
