### ISSUE TITLE
Add translation: Hindi

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#5]
**Provide the name and the two-letter code of the new language**
Hindi, `hi`

**Steps to add the translation**
- Add a folder `public/_locales/hi/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

**Comment by mdfaizan7** [comment]
I can handle this issue. Could you assign this to me?
