### ISSUE TITLE
Complete translation: Spanish

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#51]
**Provide the two-letter code of the existing language**
`es`

**Provide the lines, that are still English and should be translated**
24-25, 56-57, 60-61

**Steps to complete the translation**
- Open the corresponding file, `public/_locales/es/messages.json`
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by SabrinaFZ** [comment]
Could I be assigned to this issue?

I am spanish-speaking person 😊

**Comment by devmount** [comment]
Of course, thank you for your help!
