### ISSUE TITLE
Complete translation: French

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#52]
**Provide the two-letter code of the existing language**
`fr`

**Provide the lines, that are still English and should be translated**
24-25, 56-57, 60-61

**Steps to complete the translation**
- Open the corresponding file, `public/_locales/fr/messages.json`
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by aurelienrouze** [comment]
Hi, i opened a new PR to improve french translation. Hope it's ok for you. 

Greetings from France ;)

**Comment by devmount** [comment]
Many thanks, Aurélien!
