### ISSUE TITLE
Complete translation: Galician

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#53]
**Provide the two-letter code of the existing language**
`gl`

**Provide the lines, that are still English and should be translated**
- 24-25
- 32-33
- 40-41
- 44
- 46-47
- 71-72
- 75-76
- 81-82
- 85-86
- 93-94
- 97
- 100-101
- 104-105

**Steps to complete the translation**
- Open the corresponding file, [`public/_locales/gl/messages.json`](https://github.com/devmount/third-stats/blob/master/public/_locales/gl/messages.json)
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by devmount** [comment]
@uveic Would you like to update the Galician translation? That would be awesome!

**Comment by uveic** [comment]
@devmount Sure thing! Assign it to me, I'll do it within the next couple of days.

**Comment by devmount** [comment]
Awesome, thank you!

**Comment by uveic** [comment]
I've just done it.

https://github.com/devmount/third-stats/pull/124

I'll try to keep an eye now and then to check if a new translation is needed. Don't hesitate to get in touch if needed.

**Comment by devmount** [comment]
> I'll try to keep an eye now and then to check if a new translation is needed. Don't hesitate to get in touch if needed.

That's how open source works 💚. Thanks so much 👏🏻!
