### ISSUE TITLE
Complete translation: Hindi

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#54]
**Provide the two-letter code of the existing language**
`hi`

**Provide the lines, that are still English and should be translated**
24-25, 56-57, 60-61

**Steps to complete the translation**
- Open the corresponding file, `public/_locales/hi/messages.json`
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by kunaljain0212** [comment]
@devmount Can I work on this issue, please?

**Comment by devmount** [comment]
Of course, thanks in advance!
