### ISSUE TITLE
Complete translation: Italian

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#55]
**Provide the two-letter code of the existing language**
`it`

**Provide the lines, that are still English and should be translated**
24-25, 56-57, 60-61

**Steps to complete the translation**
- Open the corresponding file, `public/_locales/it/messages.json`
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by leobia** [comment]
Hi! I'm a native Italian speaker and I would love to help you on this issue. Can you assign it to me?

**Comment by devmount** [comment]
Awesome, many thanks for your help!
