### ISSUE TITLE
Complete translation: Polish

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#56]
**Provide the two-letter code of the existing language**
`pl`

**Provide the lines, that are still English and should be translated**
24-25, 56-57, 60-61

**Steps to complete the translation**
- Open the corresponding file, `public/_locales/pl/messages.json`
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by dfoltynski** [comment]
Hi, can u assign me to this? I am native 😊

**Comment by devmount** [comment]
Of course, thank you for your help!
