### ISSUE TITLE
Complete translation: Portuguese

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#57]
**Provide the two-letter code of the existing language**
`pt`

**Provide the lines, that are still English and should be translated**
24-25, 56-57, 60-61

**Steps to complete the translation**
- Open the corresponding file, `public/_locales/pt/messages.json`
- Translate all values of the given lines, that still have an English translation and create a pull request

**Comment by printf-ana** [comment]
Hey, i made this translations, hope help you =)
