### ISSUE TITLE
Add translation: Portuguese

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#6]
**Provide the name and the two-letter code of the new language**
Portuguese, `pt`

**Steps to add the translation**
- Add a folder `public/_locales/pt/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

**Comment by Manoj13-coder** [comment]
Assign it to me

**Comment by di3goCS** [comment]
You can assign pt-br for me?

**Comment by di3goCS** [comment]
Thanks! I'll finish soon :)
