### ISSUE TITLE
Width of charts after resizing

### ISSUE THREAD

**Issue by kerlon5** [devmount/third-stats#61]
**Describe the bug**
incorrect display width of charts after resizing on ultrawide screen

**To Reproduce**
1. Open third stats window
2. bump window to the left (or right) edge of the screen, so it uses half of the screen
3. restore the window to fullscreen view
4. See an error

**Screenshots**
![image](https://user-images.githubusercontent.com/26476861/95370150-cb8ba800-08f1-11eb-9a4a-1a5450eed78b.png)

**System:**
- OS: Windows 7
- Thunderbird Version e.g. 78.3.2 (64-Bit)
- 2560*1080 resolution

**Comment by kerlon5** [comment]
full-size screenshot from console reproduce an image with a width of 2593px

**Comment by kerlon5** [comment]
looks like `grid-template-columns repeat(4, 1fr)` for `@media (min-width: 2501px) #chart-area-main` solves it
			`

**Comment by devmount** [comment]
Good catch, thank your for reporting this. When reloading the tab after resizing, everything displays correct, so the issue is most likely caused by the responsive behavior of the charts. I'll take a look at this. If you found a fix, don't hesitate to create a PR. Thank you!
