### ISSUE TITLE
Add translation: Traditional Chinese

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#66]
**Provide the name and the two-letter code of the new language**
Traditional Chinese, `zh-tw`

**Steps to add the translation**
- Add a folder named `public/_locales/zh-tw/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

**Comment by Hsins** [comment]
Please check Pull Request #69
