### ISSUE TITLE
Add translation: Simplified Chinese

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#67]
**Provide the name and the two-letter code of the new language**
Simplified Chinese, `zh-cn`

**Steps to add the translation**
- Add a folder named `public/_locales/zh-cn/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

**Comment by jswildcards** [comment]
Hello, I'm interested in it. May I grab this issue? Thanks! 😃

**Comment by devmount** [comment]
Of course, go ahead!
