### ISSUE TITLE
Add translation: Russian

### ISSUE THREAD

**Issue by devmount** [devmount/third-stats#7]
**Provide the name and the two-letter code of the new language**
Russian, `ru`

**Steps to add the translation**
- Add a folder `public/_locales/ru/`
- Copy the file `public/_locales/en/messages.json` to your new folder
- Translate all values of that file (please leave the keys untouched!) and create a pull request

**Comment by Manoj13-coder** [comment]
assign it to me

**Comment by maria-muravyova** [comment]
I am native Russian speaker and would like to take this issue.
