### ISSUE TITLE
Locale-based start of the week

### ISSUE THREAD

**Issue by kerlon5** [devmount/third-stats#72]
Created from @ianzucker1 comment in #12 
It would be nice to have a locale-based start of the week, it can be different [around the world](https://en.wikipedia.org/wiki/Week#/media/File:First_Day_of_Week_World_Map.svg)

**Describe the solution you'd like**
It is possible to use js API call [i18n.getUILanguage()](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/i18n/getUILanguage) but I'm not sure this would work well, it's not a country, only language

**Describe alternatives you've considered**
Monday is ok for everyone

**Comment by devmount** [comment]
Thank you for this request. I agree, that it's difficult to provide some automation here based only on language.
What about making Monday the default setting and providing a manual switch for starting the week on another day?

**Comment by marcelstoer** [comment]
Since TB integrated the Lightning calendar there should be a setting for "start of the week" that you can re-use: Preferences > Calendar > Start the week on. It's `calendar.week.start`.

**Comment by devmount** [comment]
Great idea, this would be the most elegant solution in my opinion! I'll take a look at how to access that configuration from within this extension.

**Comment by devmount** [comment]
Unfortunately I didn't find a possibility to access the calendar settings - maybe you know a way @marcelstoer ? Only thing I found in the documentation are the options for the add-on itself (https://developer.thunderbird.net/add-ons/mailextensions#the-manifest-json-file).

**Comment by marcelstoer** [comment]
Sorry, can't offer much help as I'm not at all familiar with add-on development. Judging by the developer documentation I guess the idea is to expose TB settings via WebExtension APIs. However, there is no calendar API available yet. 

Maybe just assume the TB default and use https://github.com/thundernest/addon-developer-support/tree/master/auxiliary-apis/LegacyPrefs to check if the user changed its value through a user pref?

**Comment by devmount** [comment]
No problem, thanks for your help anyway! I see what I can do 👍🏻

**Comment by devmount** [comment]
One of the TB developers updated the LegacyPrefs API so that I'm now able to access the user settings and implement this feature 👍🏻 Stay tuned.
