### ISSUE TITLE
Why not Git-ignore the dist folder?

### ISSUE THREAD

**Issue by marcelstoer** [devmount/third-stats#77]
I was quite surprised to learn that `dist` is not Git-ignored. If you ever run `yarn build` locally you have to be super careful that you do not accidentally commit/push changes in your local `dist` folder upstream.

**Comment by devmount** [comment]
I see, thank you for this question. As far as I know, it's not uncommon to include the `dist` or `build` directory in a project. Personally I like to have the "cutting edge build" directly in the repository (e.g. for testing purposes) but I understand your concern. Are there any other arguments against tracking the `dist` folder despite having to pay attention on commit/push?

**Comment by marcelstoer** [comment]
I _my_ experience - 20y backend development - it's very uncommon to include any assets created by the build in the repository (e.g. `dist` for npm/yarn, `target` for Maven, `build` for Gradle). Such assets are intermediary artifacts that can be (re-)created anytime by checking out the sources and running `my-build-tool my-build-command`.

> Personally I like to have the "cutting edge build" directly in the repository (e.g. for testing purposes)

I can somewhat sympathize with this but...
- That would mean that anyone creating a PR would have to (be told to) 
  - run the build locally AND 
  - include all the changed artifacts from the `dist` directory in the PR
- One _usually_ (again, my experience) achieves this by running an automated CI build that publishes a `current_version-SNAPSHOT` such as `third-stats-0.6.0-SNAPSHOT.xpi` artifact to a public place.

P.S. Should you eventually decide to Git-ignore the `dist` folder you might have to create an `.npmignore` file as per https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package

**Comment by devmount** [comment]
Thanks you for this detailed answer! I will take some time to take a look at this and come back with a decision.

**Comment by devmount** [comment]
I decided to remove the `dist` folder from the repo. I found it to be more ease to handle for everyone. Thanks again @marcelstoer for pushing this 😎
