### ISSUE TITLE
It is showing double the total email counts in every stats

### ISSUE THREAD

**Issue by a22a-dev** [devmount/third-stats#88]
**System (please complete the following information):**
- OS: Manjaro 20.1
- Thunderbird Version 73.3.2

**Comment by devmount** [comment]
@aak9t9 Thank you for this bug report. Can you provide a little more information? Do you have multiple accounts? Is it doubled for every single account? Which account types do you use (IMAP, POP)? Which message store type (mbox or maildir)?

I'll try to reproduce this on Manjaro asap.

**Comment by aak9t9** [comment]
`Can you provide a little more information?`
Yup.
`Do you have multiple accounts?`
Yes, I have two accounts. But I tested it with single account and issue is still there.
`Is it doubled for every single account?`
Yes
`Which account types do you use (IMAP, POP)?`
IMAP, I guess. I'm not sure. How can I check that?
`Which message store type (mbox or maildir)?`
No Idea.

**Comment by devmount** [comment]
Thank you for your answers.

> IMAP, I guess. I'm not sure. How can I check that?

Account > Right Click > Settings > Server Settings: See server type at the top

> No Idea.

Account > Right Click > Settings > Server Settings: See message store type at the bottom under storage settings

**Comment by aak9t9** [comment]
Thanks. I checked. 
IMAP Mail Server & mbox it is.

**Comment by aak9t9** [comment]
Ans the problem does not occur on fresh installation of thunderbird and add on. But when launched the second or third time, this issue shows up.

**Comment by devmount** [comment]
Thank you for all these information - I'll try to reproduce this and get back to you when I have a fix.

**Comment by devmount** [comment]
Ok I'm not able to reproduce this on my system - so I have a few more questions:

1. What are the exact steps you do to reproduce the doubled stats? Install ThirdStats > open stats page (everything fine) > close Thunderbird with opened stats page > reopen Thunderbird > see doubled stats on stats page?
2. Do the numbers get tripled/quadrupled/etc. if you repeat the steps above?
3. Is every single number and every single chart value doubled or are there exceptions?

**Comment by a22a-dev** [comment]
1. Now when tested it again it is happening after every new install. I wiped the .thunderbird folder and did the whole thing again, and it is doubling, the first time itself. Also it is detecting 2 sets of folder.
![image](https://user-images.githubusercontent.com/24972285/97710672-10b28c80-1ae2-11eb-82f5-f6b66b6ff2a4.png)
2. Nope, only double.
3. No Exceptions

**Comment by a22a-dev** [comment]
I forgot to mention this before, but I'm running the beta version of thunderbird that is available in AUR.

**Comment by devmount** [comment]
> and it is doubling, the first time itself. Also it is detecting 2 sets of folder.

Although your screenshot looks quite correct. E.g. your Local Account has two folders which I assume to be the two standard folders for TB local accounts (Deleted and Outbox)...

> I'm running the beta version of thunderbird that is available in AUR.

So you're not running Thunderbird Version 73.3.2 as you first mentioned?

**Comment by a22a-dev** [comment]
Oh I'm so sorry.
First I was running the version 73.3.2 downloaded directly from thunderbird site. And the bug appeared. For which I created this issue.
Then about a week later, i formated the laptop and instead of installing from thunderbird site, i installed it from AUR version 83.0b1. 
So right I'm on version 83.0b1.

> 1. Now when tested it again it is happening after every new install. I wiped the .thunderbird folder and did the whole thing again, and it is doubling, the first time itself. Also it is detecting 2 sets of folder.
>    ![image](https://user-images.githubusercontent.com/24972285/97710672-10b28c80-1ae2-11eb-82f5-f6b66b6ff2a4.png)
> 2. Nope, only double.
> 3. No Exceptions

So Bullet 1 was in response to 83.0b1.

**Comment by devmount** [comment]
I see, no problem. I'm pretty much sure that this is not a ThirdStats issue. I searched a bit and there are a lot of old bug reports especially for Gmail accounts about doubled email counts, because of Gmails implementation of email handling.

Things you can do:

- Check with a non Gmail email address account, if the problem persists
- Try solutions like [the one posted here](http://forums.mozillazine.org/viewtopic.php?t=1680725) (unsubscribe from the "All Mails" folder), if that is still handled like this today

**Comment by a22a-dev** [comment]
Thanks!!! Second Solution Worked.

**Comment by devmount** [comment]
Awesome! Funny how solutions posted more than a decade ago are still working today 😅
