### ISSUE TITLE
Range of years is of questionable accuracy

### ISSUE THREAD

**Issue by tonewarper** [devmount/third-stats#91]
For some accounts, the stat for Total Mail (X mails within Y.Z years) displays a year range that is highly improbable. In my case, it says **50.8**, which — if correct — implies that I have received a mail from 1969… which would be 2 years before email was invented.

I can reproduce this behavior simply by navigating using the "Thunderbird Stats” button to the stats.html page for my IMAP-pulled Gmail account

What was expected is that the year range displayed is either the year the account was created (in Gmail it says 2/4/09), or the year of the oldest/first mail that was received into the account.

Maybe the header of one rotten-apple mail in my account was malformed that should be ignored by the extension because it is impossible, or another cause.

I am on MacOS Catalina 10.15.7, TB 78.3.3 (64-bit).

**Comment by devmount** [comment]
Thank you, @tonewarper for reporting this. The time span is indeed calculated based on the oldest email in your account. 50.8 years ago is very likely January 1st of 1970, which is the beginning of the unix time period. So I assume, that the date property of at least one of your emails is 0.

I will add an additional check for time range calculation to only take emails into account, that have a timestamp > 0.

**Comment by tonewarper** [comment]
Ha, that’s interesting. I’m happy to test out for you that the fix worked if you let me know when the update that includes it is released, and close the issue here. Right now I’m just curious about these stats personally but I can see your experiment with this dashboard having into a premium option (BI solution for companies who want to track or display their outbound e-mail marketing team's performance for staff motivation/management…)

**Comment by devmount** [comment]
> I’m happy to test out for you that the fix worked if you let me know when the update that includes it is released

Awesome, I'll let you know when I fixed it 👍🏻

> I can see your experiment with this dashboard having into a premium option

I don't have any plans in this direction. I just needed some analytics for my own email accounts and created this add-on. So I thought: Why not sharing the good things I built for myself with the great TB user community? That's all.

**Comment by devmount** [comment]
With #94 I implemented a possible fix. As soon as the next version gets released, the fix is public and ready for you to test.

**Comment by devmount** [comment]
@tonewarper FYI: I just released v0.6.0 of ThirdStats, it will soon be available in the Thunderbird add-on repository. Please let me know, if this issue persists.

**Comment by tonewarper** [comment]
Fixed, Andreas ! 11.7 years showing now… much more realistic!
