### ISSUE TITLE
Show summarized stats of all accounts

### ISSUE THREAD

**Issue by dynobo** [devmount/third-stats#92]
**Is your feature request related to a problem? Please describe.**
Currently I can select a specific account, for which the stats are calculated. I use different accounts + local accounts for organizing all my mails, but still would love to have an overview on the overall stats.

**Describe the solution you'd like**
A simple solution could be to add an additional entry "all" to the "accounts"-dropdown (in case there is more than one account in the thunderbird profile) which generates statistics over all accounts.

**Describe alternatives you've considered**
The only alternative would be to switch to a different workflow mode and move all mails to a single account. But that would impact my productivity a lot.

**Additional context**
n/a

**Additional note:** Thanks for the great extension! I love it :-)

**Comment by devmount** [comment]
Thanks @dynobo for this request. I like it and definitely see the advantage for users with a lot of accounts. As there are currently some bugs to fix, this won't be in the next release, but maby the one after.

You're very welcome, I'm glad you like this add-on 😊

**Comment by devmount** [comment]
This feature took a lot more time than expected, but it's now implemented with #196 and will be part of the next release. Please test it and if you have any problems, file a bug report. Happy new year 🎉
